package main

import (
	"bufio"
	"fmt"
	"os"
	"os/exec"
	"strings"
	"time"
)

func isSecret(name string) bool {
	secrets := []string{"KEY", "SECRET", "TOKEN", "PASSWORD", "AUTH", "CREDS", "PRIVATE"}
	for _, s := range secrets {
		if strings.Contains(strings.ToUpper(name), s) {
			return true
		}
	}
	return false
}

func main() {
	envPath := ".env"
	examplePath := ".env.example"
	dataset := "tank/monorepo"

	fmt.Printf("[vault] %s Starting sync\n", time.Now().Format("15:04:05"))

	// 1. ZFS Snapshot
	snapName := fmt.Sprintf("%s@env-vault-%s", dataset, time.Now().Format("20060102-150405"))
	cmd := exec.Command("sudo", "zfs", "snapshot", snapName)
	if err := cmd.Run(); err == nil {
		fmt.Printf("[vault] ZFS snapshot: %s\n", snapName)
	}

	// 2. Sync .env -> .env.example
	file, err := os.Open(envPath)
	if err != nil {
		fmt.Printf("ERROR: %v\n", err)
		os.Exit(1)
	}
	defer file.Close()

	out, err := os.Create(examplePath)
	if err != nil {
		fmt.Printf("ERROR: %v\n", err)
		os.Exit(1)
	}
	defer out.Close()

	fmt.Fprintln(out, "# =============================================================================")
	fmt.Fprintln(out, "# .env.example — AUTO-GENERATED by vault.go")
	fmt.Fprintln(out, "# =============================================================================")

	scanner := bufio.NewScanner(file)
	secretCount := 0
	for scanner.Scan() {
		line := scanner.Text()
		if line == "" || strings.HasPrefix(line, "#") {
			fmt.Fprintln(out, line)
			continue
		}

		parts := strings.SplitN(line, "=", 2)
		if len(parts) == 2 {
			name := parts[0]
			if isSecret(name) {
				fmt.Fprintf(out, "%s=${%s}\n", name, name)
				secretCount++
			} else {
				fmt.Fprintln(out, line)
			}
		}
	}

	fmt.Printf("[vault] Done. Redacted %d secrets.\n", secretCount)
}
