import z from 'zod';
import { addressTypeZod } from './crm_enums.zod.js';
import { zTimestamps, zVarchar } from './zod_utils.js';

export const addressMandatoryZod = z.object({
	clienteId: z.uuid(),
	rua: zVarchar(1, 255),
	numero: zVarchar(1, 20),
	bairro: zVarchar(1, 100),
	cep: zVarchar(8, 9),
	cidade: zVarchar(1, 100),
	estado: zVarchar(2, 2),
});

export const addressOptionalZod = z.object({
	tipo: addressTypeZod.nullable(),
	complemento: zVarchar(0, 100).nullable(),
});

const addressAutoGeneratedZod = z.object({
	addressId: z.uuid(),
});

export const addressCreateInputZod = addressMandatoryZod.extend(addressOptionalZod.partial().shape);
export const addressSelectAllZod = addressMandatoryZod
	.extend(addressOptionalZod.shape)
	.extend(addressAutoGeneratedZod.shape)
	.extend(zTimestamps);

export const addressGetByIdZod = z.object({ addressId: z.uuid() });
export const addressesByClientZod = z.object({ clienteId: z.uuid() });

export type AddressCreateInput = z.infer<typeof addressCreateInputZod>;
export type AddressSelectAll = z.infer<typeof addressSelectAllZod>;
