import z from "zod";
import { apiProductRequestStatusZod, apiRequestMethodZod } from "./enums.zod.js";
import { zSmallint, zString, zTimestamps } from "./zod_utils.js";

const apiProductRequestLogAutoGeneratedZod = z.object({
  apiProductRequestId: z.ulid(),
});

const apiProductRequestLogMandatoryZod = z.object({
  teamId: z.uuid(),
  teamUserReferenceId: zString,
  method: apiRequestMethodZod,
  path: zString,
  ip: zString,
  status: apiProductRequestStatusZod,
});

const apiProductRequestOptionalZod = z.object({
  requestBodyText: zString.nullable(),
  requestBodyJson: z.any().nullable(),
  responseText: zString.nullable(),
  responseJson: z.any().nullable(),
  responseTime: zSmallint(0),
});

export const apiProductRequestLogCreateInputZod = apiProductRequestLogMandatoryZod.extend(apiProductRequestOptionalZod.partial().shape);
export type ApiProductRequestLogCreateInput = z.infer<typeof apiProductRequestLogCreateInputZod>;

export const apiProductRequestLogUpdateInputZod = apiProductRequestLogMandatoryZod.extend(apiProductRequestOptionalZod.shape).extend(zTimestamps).partial();
export type ApiProductRequestLogUpdateInput = z.infer<typeof apiProductRequestLogUpdateInputZod>;

export const apiProductRequestLogSelectAllZod = apiProductRequestLogMandatoryZod.extend(apiProductRequestOptionalZod.shape).extend(zTimestamps).extend(apiProductRequestLogAutoGeneratedZod.shape);
export type ApiProductRequestLogSelectAll = z.infer<typeof apiProductRequestLogSelectAllZod>;

export const apiProductRequestLogGetByIdInputZod = z.object({
  apiProductRequestId: z.string(),
});
export type ApiProductRequestLogGetByIdInput = z.infer<typeof apiProductRequestLogGetByIdInputZod>;

export const apiProductRequestLogGetByTeamInputZod = z.object({
  teamId: z.uuid(),
  page: z.number().int().min(1).default(1),
  limit: z.number().int().min(1).max(100).default(20),
  status: apiProductRequestStatusZod.optional(),
  startDate: z.number().optional(),
  endDate: z.number().optional(),
});
export type ApiProductRequestLogGetByTeamInput = z.infer<typeof apiProductRequestLogGetByTeamInputZod>;