import z from "zod";
import { clientTypeZod } from "./crm_enums.zod.js";
import { zString, zTimestamps, zVarchar } from "./zod_utils.js";

export const clientMandatoryZod = z.object({
	nome: zVarchar(1, 255),
	tipo: clientTypeZod,
});

export const clientOptionalZod = z.object({
	email: z.string().email().nullable(),
	telefone: zVarchar(0, 30).nullable(),
	cpfCnpj: zVarchar(0, 18).nullable(),
	responsavelId: z.uuid().nullable(),
	tags: z.array(z.string()).nullable(),
	ativo: z.boolean(),
});

const clientAutoGeneratedZod = z.object({
	clientId: z.uuid(),
});

export const clientCreateInputZod = clientMandatoryZod.extend(clientOptionalZod.partial().shape);
export const clientUpdateInputZod = clientMandatoryZod
	.extend(clientOptionalZod.shape)
	.extend(clientAutoGeneratedZod.shape)
	.partial()
	.required({ clientId: true });
export const clientSelectAllZod = clientMandatoryZod
	.extend(clientOptionalZod.shape)
	.extend(clientAutoGeneratedZod.shape)
	.extend(zTimestamps);

export const clientGetByIdZod = z.object({ clientId: z.uuid() });

export const listClientsFilterZod = z.object({
	tipo: clientTypeZod.optional(),
	responsavelId: z.uuid().optional(),
	ativo: z.boolean().optional(),
	search: zString.optional(),
});

export type ClientCreateInput = z.infer<typeof clientCreateInputZod>;
export type ClientUpdateInput = z.infer<typeof clientUpdateInputZod>;
export type ClientSelectAll = z.infer<typeof clientSelectAllZod>;
export type ListClientsFilter = z.infer<typeof listClientsFilterZod>;
