import z from "zod";
import { contractFrequencyZod, contractStatusZod, contractTypeZod } from "./crm_enums.zod.js";
import { zText, zTimestamps } from "./zod_utils.js";

const contractMandatoryZod = z.object({
	clienteId: z.string().uuid(),
	tipo: contractTypeZod,
	status: contractStatusZod,
	dataInicio: z.string().date(),
});

const contractOptionalZod = z.object({
	descricao: zText().nullable(),
	dataFim: z.string().date().nullable(),
	valor: z.number().min(0).nullable(),
	frequencia: contractFrequencyZod.nullable(),
	observacoes: zText().nullable(),
	motivoCancelamento: zText().nullable(),
});

const contractAutoGeneratedZod = z.object({
	contractId: z.string().uuid(),
});

export const contractCreateInputZod = contractMandatoryZod.extend(
	contractOptionalZod.partial().shape,
);
export const contractUpdateInputZod = contractMandatoryZod
	.extend(contractOptionalZod.shape)
	.extend(contractAutoGeneratedZod.shape)
	.partial()
	.required({ contractId: true });
export const contractSelectAllZod = contractMandatoryZod
	.extend(contractOptionalZod.shape)
	.extend(contractAutoGeneratedZod.shape)
	.extend(zTimestamps);
export const contractGetByIdZod = z.object({ contractId: z.string().uuid() });
export const listContractFilterZod = z.object({
	clienteId: z.string().uuid().optional(),
	status: contractStatusZod.optional(),
	tipo: contractTypeZod.optional(),
	dataInicio: z.string().date().optional(),
	dataFim: z.string().date().optional(),
});

export type ContractCreateInput = z.infer<typeof contractCreateInputZod>;
export type ContractUpdateInput = z.infer<typeof contractUpdateInputZod>;
export type ContractSelectAll = z.infer<typeof contractSelectAllZod>;
export type ContractGetById = z.infer<typeof contractGetByIdZod>;
export type ListContractFilter = z.infer<typeof listContractFilterZod>;
