import z from "zod";
import { zTimestamps, zVarchar } from "./zod_utils.js";

export const contactMandatoryZod = z.object({
	clienteId: z.uuid(),
	nome: zVarchar(1, 255),
});

export const contactOptionalZod = z.object({
	email: z.string().email().nullable(),
	telefone: zVarchar(0, 30).nullable(),
	cargo: zVarchar(0, 100).nullable(),
	isPrimary: z.boolean(),
});

const contactAutoGeneratedZod = z.object({
	contactId: z.uuid(),
});

export const contactCreateInputZod = contactMandatoryZod.extend(contactOptionalZod.partial().shape);
export const contactSelectAllZod = contactMandatoryZod
	.extend(contactOptionalZod.shape)
	.extend(contactAutoGeneratedZod.shape)
	.extend(zTimestamps);

export const contactGetByIdZod = z.object({ contactId: z.uuid() });
export const contactsByClientZod = z.object({ clienteId: z.uuid() });

export type ContactCreateInput = z.infer<typeof contactCreateInputZod>;
export type ContactSelectAll = z.infer<typeof contactSelectAllZod>;
