import z from 'zod';
import { editorialChannelZod, editorialFormatZod, editorialStatusZod } from './crm_enums.zod.js';
import { zText, zTimestamps, zVarchar } from './zod_utils.js';

const editorialMandatoryZod = z.object({
	titulo: zVarchar(1, 255),
	canal: editorialChannelZod,
	formato: editorialFormatZod,
	status: editorialStatusZod,
	dataPublicacao: z.string().date(),
});

const editorialOptionalZod = z.object({
	pauta: zText().nullable(),
	copy: zText().nullable(),
	cta: zVarchar(0, 255).nullable(),
	observacoes: zText().nullable(),
	campanhaId: z.string().uuid().nullable(),
});

const editorialAutoGeneratedZod = z.object({
	editorialId: z.string().uuid(),
	teamId: z.string().uuid(),
});

export const editorialCreateInputZod = editorialMandatoryZod
	.extend(editorialOptionalZod.partial().shape);
export const editorialUpdateInputZod = editorialMandatoryZod
	.extend(editorialOptionalZod.shape)
	.extend(editorialAutoGeneratedZod.shape)
	.partial()
	.required({ editorialId: true });
export const editorialSelectAllZod = editorialMandatoryZod
	.extend(editorialOptionalZod.shape)
	.extend(editorialAutoGeneratedZod.shape)
	.extend(zTimestamps)
	.extend({ teamId: z.string().uuid() });
export const editorialGetByIdZod = z.object({ editorialId: z.string().uuid() });
export const listEditorialFilterZod = z.object({
	status: editorialStatusZod.optional(),
	canal: editorialChannelZod.optional(),
	formato: editorialFormatZod.optional(),
	dataInicio: z.string().date().optional(),
	dataFim: z.string().date().optional(),
});

export type EditorialCreateInput = z.infer<typeof editorialCreateInputZod>;
export type EditorialUpdateInput = z.infer<typeof editorialUpdateInputZod>;
export type EditorialSelectAll = z.infer<typeof editorialSelectAllZod>;
export type EditorialGetById = z.infer<typeof editorialGetByIdZod>;
export type ListEditorialFilter = z.infer<typeof listEditorialFilterZod>;
