import z from "zod";
import { EQUIPMENT_STATUS_ENUM } from "./crm_enums.zod.js";
import { zTimestamps, zVarchar, zText } from "./zod_utils.js";

const equipmentMandatoryZod = z.object({
	clienteId: z.uuid(),
	nome: zVarchar(1, 255),
	tipo: zVarchar(0, 100),
	status: z.enum(EQUIPMENT_STATUS_ENUM),
});

const equipmentOptionalZod = z.object({
	unitId: z.uuid().nullable(),
	marca: zVarchar(0, 100).nullable(),
	modelo: zVarchar(0, 100).nullable(),
	numeroDeSerie: zVarchar(0, 100).nullable(),
	capacidadeBtu: z.int().nullable(),
	anoFabricacao: z.int().nullable(),
	dataInstalacao: z.string().nullable(),
	ultimaManutencao: z.string().nullable(),
	observacoes: zText().nullable(),
	ativo: z.boolean(),
});

const equipmentAutoGeneratedZod = z.object({
	equipmentId: z.uuid(),
});

export const equipmentCreateInputZod = equipmentMandatoryZod.extend(equipmentOptionalZod.partial().shape);
export const equipmentUpdateInputZod = equipmentMandatoryZod
	.extend(equipmentOptionalZod.shape)
	.extend(equipmentAutoGeneratedZod.shape)
	.partial()
	.required({ equipmentId: true });
export const equipmentSelectAllZod = equipmentMandatoryZod
	.extend(equipmentOptionalZod.shape)
	.extend(equipmentAutoGeneratedZod.shape)
	.extend(zTimestamps);

export const equipmentGetByIdZod = z.object({ equipmentId: z.uuid() });
export const equipmentsByClientZod = z.object({ clienteId: z.uuid() });
export const equipmentsByUnitZod = z.object({ unitId: z.uuid() });
export const listEquipmentFilterZod = z.object({
	clienteId: z.uuid().optional(),
	unitId: z.uuid().optional(),
	status: z.enum(EQUIPMENT_STATUS_ENUM).optional(),
	ativo: z.boolean().optional(),
});

export type EquipmentCreateInput = z.infer<typeof equipmentCreateInputZod>;
export type EquipmentUpdateInput = z.infer<typeof equipmentUpdateInputZod>;
export type EquipmentSelectAll = z.infer<typeof equipmentSelectAllZod>;
export type ListEquipmentFilter = z.infer<typeof listEquipmentFilterZod>;
