import z from "zod";
import { zString, zTimestamps } from "./zod_utils.js";

export const journalEntryMandatoryZod = z.object({
	prompt: zString.min(1, "Prompt is required").max(500),
	promptId: z.ulid(),
	content: zString.min(1, "Content is required").max(50000),
	authorUserId: z.uuid(),
});

export const journalEntryAutoGeneratedZod = z.object({
	journalEntryId: z.ulid(),
});

export const journalEntryOptionalZod = z.object({
});

export const journalEntryCreateInputZod = journalEntryMandatoryZod.omit({ authorUserId: true }).extend(journalEntryOptionalZod.partial().shape);
export type JournalEntryCreateInput = z.infer<typeof journalEntryCreateInputZod>;

export const journalEntryUpdateInputZod = journalEntryMandatoryZod.extend(journalEntryOptionalZod.shape).extend(zTimestamps).partial();
export type JournalEntryUpdateInput = z.infer<typeof journalEntryUpdateInputZod>;

export const journalEntrySelectAllZod = journalEntryMandatoryZod.extend(journalEntryOptionalZod.shape).extend(zTimestamps).extend(journalEntryAutoGeneratedZod.shape);
export type JournalEntrySelectAll = z.infer<typeof journalEntrySelectAllZod>;

export const journalEntryGetByIdZod = z.object({
	journalEntryId: z.uuid(),
});
export type GetJournalEntryByIdInput = z.infer<typeof journalEntryGetByIdZod>;

export const journalEntryGetByUserZod = z.object({
	authorUserId: zString,
});
export type GetJournalEntriesByUserInput = z.infer<typeof journalEntryGetByUserZod>;
