import z from 'zod';
import { kanbanCardPriorityZod, kanbanCardStatusZod } from './crm_enums.zod.js';
import { zText, zTimestamps } from './zod_utils.js';

// ---------------------------------------------------------------------------
// KanbanBoard
// ---------------------------------------------------------------------------

const boardMandatoryZod = z.object({
	nome: zText(1),
	setor: zText(1),
});

const boardOptionalZod = z.object({
	descricao: zText().nullable(),
	cor: z.string().max(7).nullable(),
});

const boardAutoGeneratedZod = z.object({
	boardId: z.string().uuid(),
});

export const boardCreateInputZod = boardMandatoryZod.extend(boardOptionalZod.partial().shape);
export const boardUpdateInputZod = boardMandatoryZod
	.extend(boardOptionalZod.shape)
	.extend(boardAutoGeneratedZod.shape)
	.partial()
	.required({ boardId: true });
export const boardSelectAllZod = boardMandatoryZod
	.extend(boardOptionalZod.shape)
	.extend(boardAutoGeneratedZod.shape)
	.extend(zTimestamps);
export const boardGetByIdZod = z.object({ boardId: z.string().uuid() });
export const listBoardFilterZod = z.object({
	setor: zText().optional(),
});

export type BoardCreateInput = z.infer<typeof boardCreateInputZod>;
export type BoardUpdateInput = z.infer<typeof boardUpdateInputZod>;
export type BoardSelectAll = z.infer<typeof boardSelectAllZod>;

// ---------------------------------------------------------------------------
// KanbanColumn
// ---------------------------------------------------------------------------

const columnMandatoryZod = z.object({
	boardId: z.string().uuid(),
	nome: zText(1),
	ordem: z.number().int().min(0),
});

const columnOptionalZod = z.object({
	limite: z.number().int().min(0).nullable(),
});

const columnAutoGeneratedZod = z.object({
	columnId: z.string().uuid(),
});

export const columnCreateInputZod = columnMandatoryZod.extend(columnOptionalZod.partial().shape);
export const columnUpdateInputZod = columnMandatoryZod
	.extend(columnOptionalZod.shape)
	.extend(columnAutoGeneratedZod.shape)
	.partial()
	.required({ columnId: true });
export const columnSelectAllZod = columnMandatoryZod
	.extend(columnOptionalZod.shape)
	.extend(columnAutoGeneratedZod.shape);

export type ColumnCreateInput = z.infer<typeof columnCreateInputZod>;
export type ColumnUpdateInput = z.infer<typeof columnUpdateInputZod>;
export type ColumnSelectAll = z.infer<typeof columnSelectAllZod>;

// ---------------------------------------------------------------------------
// KanbanCard
// ---------------------------------------------------------------------------

const cardMandatoryZod = z.object({
	columnId: z.string().uuid(),
	titulo: zText(1),
});

const cardOptionalZod = z.object({
	descricao: zText().nullable(),
	prioridade: kanbanCardPriorityZod.nullable(),
	status: kanbanCardStatusZod.nullable(),
	responsavelId: z.string().uuid().nullable(),
	dataVencimento: z.string().date().nullable(),
	ordem: z.number().int().min(0).nullable(),
});

const cardAutoGeneratedZod = z.object({
	cardId: z.string().uuid(),
});

export const cardCreateInputZod = cardMandatoryZod.extend(cardOptionalZod.partial().shape);
export const cardUpdateInputZod = cardMandatoryZod
	.extend(cardOptionalZod.shape)
	.extend(cardAutoGeneratedZod.shape)
	.partial()
	.required({ cardId: true });
export const cardSelectAllZod = cardMandatoryZod
	.extend(cardOptionalZod.shape)
	.extend(cardAutoGeneratedZod.shape)
	.extend(zTimestamps);
export const cardGetByIdZod = z.object({ cardId: z.string().uuid() });
export const listCardFilterZod = z.object({
	columnId: z.string().uuid().optional(),
	boardId: z.string().uuid().optional(),
	status: kanbanCardStatusZod.optional(),
	responsavelId: z.string().uuid().optional(),
});

export type CardCreateInput = z.infer<typeof cardCreateInputZod>;
export type CardUpdateInput = z.infer<typeof cardUpdateInputZod>;
export type CardSelectAll = z.infer<typeof cardSelectAllZod>;
