import z from 'zod';
import { leadSourceZod, leadStatusZod } from './crm_enums.zod.js';
import { zString, zText, zTimestamps, zVarchar } from './zod_utils.js';

export const leadMandatoryZod = z.object({
	nome: zVarchar(1, 255),
	origem: leadSourceZod,
	status: leadStatusZod,
});

export const leadOptionalZod = z.object({
	email: z.string().email().nullable(),
	telefone: zVarchar(0, 30).nullable(),
	canal: zVarchar(0, 100).nullable(),
	responsavelId: z.uuid().nullable(),
	observacoes: zText().nullable(),
	convertidoClienteId: z.uuid().nullable(),
});

const leadAutoGeneratedZod = z.object({
	leadId: z.uuid(),
});

export const leadCreateInputZod = leadMandatoryZod.extend(leadOptionalZod.partial().shape);
export const leadUpdateInputZod = leadMandatoryZod
	.extend(leadOptionalZod.shape)
	.extend(leadAutoGeneratedZod.shape)
	.partial()
	.required({ leadId: true });
export const leadSelectAllZod = leadMandatoryZod
	.extend(leadOptionalZod.shape)
	.extend(leadAutoGeneratedZod.shape)
	.extend(zTimestamps);

export const leadGetByIdZod = z.object({ leadId: z.uuid() });

export const listLeadsFilterZod = z.object({
	status: leadStatusZod.optional(),
	origem: leadSourceZod.optional(),
	responsavelId: z.uuid().optional(),
	search: zString.optional(),
});

export type LeadCreateInput = z.infer<typeof leadCreateInputZod>;
export type LeadUpdateInput = z.infer<typeof leadUpdateInputZod>;
export type LeadSelectAll = z.infer<typeof leadSelectAllZod>;
export type ListLeadsFilter = z.infer<typeof listLeadsFilterZod>;
