import z from "zod";
import { zTimestamps, zVarchar } from "./zod_utils.js";

const materialItemMandatoryZod = z.object({
	serviceOrderId: z.string().uuid(),
	descricao: zVarchar(1, 255),
	quantidade: z.number().positive(),
	unidade: zVarchar(1, 20),
});

const materialItemOptionalZod = z.object({
	valorUnitario: z.number().nonnegative().nullable(),
});

const materialItemAutoGeneratedZod = z.object({
	materialItemId: z.string().uuid(),
});

export const materialItemCreateInputZod = materialItemMandatoryZod.extend(
	materialItemOptionalZod.partial().shape,
);

export const materialItemUpdateInputZod = materialItemMandatoryZod
	.extend(materialItemOptionalZod.shape)
	.extend(materialItemAutoGeneratedZod.shape)
	.partial()
	.required({ materialItemId: true });

export const materialItemSelectAllZod = materialItemMandatoryZod
	.extend(materialItemOptionalZod.shape)
	.extend(materialItemAutoGeneratedZod.shape)
	.extend(zTimestamps);

export const materialItemGetByIdZod = z.object({ materialItemId: z.string().uuid() });
export const materialItemsByServiceOrderZod = z.object({ serviceOrderId: z.string().uuid() });

export type MaterialItemCreateInput = z.infer<typeof materialItemCreateInputZod>;
export type MaterialItemUpdateInput = z.infer<typeof materialItemUpdateInputZod>;
export type MaterialItemSelectAll = z.infer<typeof materialItemSelectAllZod>;
export type MaterialItemGetById = z.infer<typeof materialItemGetByIdZod>;
