import z from "zod";
import { zString, zTimestamps } from "./zod_utils.js";

export const postMandatoryZod = z.object({
  title: zString.min(1, "Title is required"),
  content: zString.min(1, "Content is required"),
  authorUserId: z.uuid(),
});

export const postAutoGeneratedZod = z.object({
  postId: z.ulid(),
});

export const postOptionalZod = z.object({
});

export const postCreateInputZod = postMandatoryZod;
export type PostCreateInput = z.infer<typeof postCreateInputZod>;

export const postUpdateInputZod = postMandatoryZod.extend(postOptionalZod.shape).extend(zTimestamps).partial();
export type PostUpdateInput = z.infer<typeof postUpdateInputZod>;

export const postSelectAllZod = postMandatoryZod.extend(postOptionalZod.shape).extend(zTimestamps).extend(postAutoGeneratedZod.shape); 
export type PostSelectAll = z.infer<typeof postSelectAllZod>;

export const postGetByIdZod = z.object({
  postId: z.ulid(),
});
export type GetPostByIdInput = z.infer<typeof postGetByIdZod>;

export const postGetByAuthorZod = z.object({
  authorUserId: z.uuid(),
});
export type GetPostsByAuthorInput = z.infer<typeof postGetByAuthorZod>;