import z from "zod";
import { zString, zTimestamps } from "./zod_utils.js";

export const promptMandatoryZod = z.object({
	text: zString.min(1, "Prompt text is required").max(500),
});

export const promptOptionalZod = z.object({
	category: zString.max(100).nullable(),
	tags: z.array(zString).nullable(),
	isActive: z.boolean(),
});

const promptAutoGeneratedZod = z.object({
	promptId: z.ulid(),
});

export const promptCreateInputZod = promptMandatoryZod.extend(promptOptionalZod.partial().shape);
export type PromptCreateInput = z.infer<typeof promptCreateInputZod>;

export const promptUpdateInputZod = promptMandatoryZod.extend(promptOptionalZod.shape).extend(zTimestamps).partial();
export type PromptUpdateInput = z.infer<typeof promptUpdateInputZod>;

export const promptSelectAllZod = promptMandatoryZod.extend(promptOptionalZod.shape).extend(zTimestamps).extend(promptAutoGeneratedZod.shape);
export type PromptSelectAll = z.infer<typeof promptSelectAllZod>;

export const promptGetByIdZod = z.object({
	promptId: z.uuid(),
});
export type GetPromptByIdInput = z.infer<typeof promptGetByIdZod>;

export const promptGetByCategoryZod = z.object({
	category: zString,
});
export type GetPromptsByCategoryInput = z.infer<typeof promptGetByCategoryZod>;

export const promptGetActiveZod = z.object({
	isActive: z.boolean().default(true),
});
export type GetActivePromptsInput = z.infer<typeof promptGetActiveZod>;
