import z from 'zod';
import { reminderStatusZod, reminderTypeZod } from './crm_enums.zod.js';
import { zText, zTimestamps, zVarchar } from './zod_utils.js';

const reminderMandatoryZod = z.object({
	clienteId: z.string().uuid(),
	tipo: reminderTypeZod,
	status: reminderStatusZod,
	dataLembrete: z.string().date(),
	titulo: zVarchar(1, 255),
});

const reminderOptionalZod = z.object({
	descricao: zText().nullable(),
	scheduleId: z.string().uuid().nullable(),
	contractId: z.string().uuid().nullable(),
});

const reminderAutoGeneratedZod = z.object({
	reminderId: z.string().uuid(),
});

export const reminderCreateInputZod = reminderMandatoryZod.extend(
	reminderOptionalZod.partial().shape,
);
export const reminderUpdateInputZod = reminderMandatoryZod
	.extend(reminderOptionalZod.shape)
	.extend(reminderAutoGeneratedZod.shape)
	.partial()
	.required({ reminderId: true });
export const reminderSelectAllZod = reminderMandatoryZod
	.extend(reminderOptionalZod.shape)
	.extend(reminderAutoGeneratedZod.shape)
	.extend(zTimestamps);
export const reminderGetByIdZod = z.object({ reminderId: z.string().uuid() });
export const listReminderFilterZod = z.object({
	clienteId: z.string().uuid().optional(),
	status: reminderStatusZod.optional(),
	tipo: reminderTypeZod.optional(),
	dataInicio: z.string().date().optional(),
	dataFim: z.string().date().optional(),
});

export type ReminderCreateInput = z.infer<typeof reminderCreateInputZod>;
export type ReminderUpdateInput = z.infer<typeof reminderUpdateInputZod>;
export type ReminderSelectAll = z.infer<typeof reminderSelectAllZod>;
export type ReminderGetById = z.infer<typeof reminderGetByIdZod>;
export type ListReminderFilter = z.infer<typeof listReminderFilterZod>;
