import z from "zod";
import { scheduleStatusZod, serviceTypeZod } from "./crm_enums.zod.js";
import { zTimestamps, zText, zVarchar } from "./zod_utils.js";

const scheduleMandatoryZod = z.object({
  clienteId: z.string().uuid(),
  dataHora: z.string().datetime(), // ISO 8601
  tipo: serviceTypeZod,
  status: scheduleStatusZod,
});

const scheduleOptionalZod = z.object({
  unitId: z.string().uuid().nullable(),
  equipmentId: z.string().uuid().nullable(),
  tecnicoId: z.string().uuid().nullable(),
  duracaoMinutos: z.number().int().min(15).max(480),
  descricao: zText().nullable(),
  observacoes: zText().nullable(),
  motivoCancelamento: zText().nullable(),
});

const scheduleAutoGeneratedZod = z.object({
  scheduleId: z.string().uuid(),
});

export const scheduleCreateInputZod = scheduleMandatoryZod.extend(scheduleOptionalZod.partial().shape);
export const scheduleUpdateInputZod = scheduleMandatoryZod
  .extend(scheduleOptionalZod.shape)
  .extend(scheduleAutoGeneratedZod.shape)
  .partial()
  .required({ scheduleId: true });
export const scheduleSelectAllZod = scheduleMandatoryZod
  .extend(scheduleOptionalZod.shape)
  .extend(scheduleAutoGeneratedZod.shape)
  .extend(zTimestamps);
export const scheduleGetByIdZod = z.object({ scheduleId: z.string().uuid() });
export const listScheduleFilterZod = z.object({
  clienteId: z.string().uuid().optional(),
  tecnicoId: z.string().uuid().optional(),
  status: scheduleStatusZod.optional(),
  tipo: serviceTypeZod.optional(),
  dataInicio: z.string().datetime().optional(),
  dataFim: z.string().datetime().optional(),
});

export type ScheduleCreateInput = z.infer<typeof scheduleCreateInputZod>;
export type ScheduleUpdateInput = z.infer<typeof scheduleUpdateInputZod>;
export type ScheduleSelectAll = z.infer<typeof scheduleSelectAllZod>;
export type ListScheduleFilter = z.infer<typeof listScheduleFilterZod>;
