import z from "zod";
import { serviceOrderStatusZod, serviceTypeZod } from "./crm_enums.zod.js";
import { zText, zTimestamps } from "./zod_utils.js";

const serviceOrderMandatoryZod = z.object({
	clienteId: z.string().uuid(),
	tipo: serviceTypeZod,
	status: serviceOrderStatusZod,
	dataAbertura: z.string().datetime({ local: true }),
});

const serviceOrderOptionalZod = z.object({
	scheduleId: z.string().uuid().nullable(),
	unitId: z.string().uuid().nullable(),
	equipmentId: z.string().uuid().nullable(),
	tecnicoId: z.string().uuid().nullable(),
	dataFechamento: z.string().datetime({ local: true }).nullable(),
	descricao: zText().nullable(),
	observacoes: zText().nullable(),
});

const serviceOrderAutoGeneratedZod = z.object({
	serviceOrderId: z.string().uuid(),
	numero: z.string(),
});

export const serviceOrderCreateInputZod = serviceOrderMandatoryZod.extend(
	serviceOrderOptionalZod.partial().shape,
);

export const serviceOrderUpdateInputZod = serviceOrderMandatoryZod
	.extend(serviceOrderOptionalZod.shape)
	.extend(serviceOrderAutoGeneratedZod.shape)
	.partial()
	.required({ serviceOrderId: true });

export const serviceOrderSelectAllZod = serviceOrderMandatoryZod
	.extend(serviceOrderOptionalZod.shape)
	.extend(serviceOrderAutoGeneratedZod.shape)
	.extend(zTimestamps);

export const serviceOrderGetByIdZod = z.object({ serviceOrderId: z.string().uuid() });

export const listServiceOrdersFilterZod = z.object({
	clienteId: z.string().uuid().optional(),
	tecnicoId: z.string().uuid().optional(),
	equipmentId: z.string().uuid().optional(),
	status: serviceOrderStatusZod.optional(),
	tipo: serviceTypeZod.optional(),
	search: z.string().optional(),
});

export type ServiceOrderCreateInput = z.infer<typeof serviceOrderCreateInputZod>;
export type ServiceOrderUpdateInput = z.infer<typeof serviceOrderUpdateInputZod>;
export type ServiceOrderSelectAll = z.infer<typeof serviceOrderSelectAllZod>;
export type ServiceOrderGetById = z.infer<typeof serviceOrderGetByIdZod>;
export type ListServiceOrdersFilter = z.infer<typeof listServiceOrdersFilterZod>;
