import z from "zod";
import { apiProductSkuZod } from "./enums.zod.js";
import { webhookCallQueueSelectAllZod } from "./webhook_call_queue.zod.js";
import { zSmallint, zString, zTimeEpoch, zTimestamps } from "./zod_utils.js";

const subscriptionAutoGeneratedZod = z.object({
  subscriptionId: z.ulid(),
});

const subscriptionMandatoryZod = z.object({
  expiresAt: zTimeEpoch,
  maxRequests: zSmallint(0),
  apiProductSku: apiProductSkuZod,
  requestsConsumed: zSmallint(0).default(0),
  teamId: z.uuid(),
  teamUserReferenceId: zString,
});

const subscriptionOptionalZod = z.object({
  billingInvoiceNumber: zString.nullable(),
  billingInvoiceDate: zTimeEpoch.nullable(),
  notifiedAt90PercentUse: zTimeEpoch.nullable(),
  paymentReceivedDate: zTimeEpoch.nullable(),
  paymentTransactionId: zString.nullable(),
});

export const subscriptionRelationsZod = z.object({
  webHooksCalled: z.array(webhookCallQueueSelectAllZod).nullable(),
});

export const subscriptionCreateInputZod = subscriptionMandatoryZod.extend(subscriptionOptionalZod.partial().shape);
export type SubscriptionCreateInput = z.infer<typeof subscriptionCreateInputZod>;

export const subscriptionUpdateInputZod = subscriptionMandatoryZod.extend(subscriptionOptionalZod.shape).extend(zTimestamps).partial();
export type SubscriptionUpdateInput = z.infer<typeof subscriptionUpdateInputZod>;

export const subscriptionSelectAllZod = subscriptionMandatoryZod.extend(subscriptionOptionalZod.shape).extend(subscriptionAutoGeneratedZod.shape).extend(zTimestamps);
export type SubscriptionSelectAll = z.infer<typeof subscriptionSelectAllZod>;

export const subscriptionGetByIdInputZod = z.object({
  subscriptionId: z.string(),
});
export type SubscriptionGetByIdInput = z.infer<typeof subscriptionGetByIdInputZod>;

export const subscriptionGetActiveByTeamInputZod = z.object({
  teamId: z.uuid(),
  apiProductSku: apiProductSkuZod.optional(),
});
export type SubscriptionGetActiveByTeamInput = z.infer<typeof subscriptionGetActiveByTeamInputZod>;