import z from "zod";
import { zSmallint, zString } from "./zod_utils.js";

const teamAutoGeneratedZod = z.object({
  teamId: z.uuid(),
});

const teamMandatoryZod = z.object({
  allowedDomains: z.array(zString).default([]),
  allowedIPs: z.array(zString).default([]),
  apiSecretHash: zString,
  name: zString,
  rateLimitPerMinute: zSmallint(),
});

const teamOptionalZod = z.object({
  subscriptionAlertWebhookUrl: zString.nullable(),
  subscriptionAlertWebhookBearerToken: zString.nullable(),
});

export const teamCreateInputZod = teamMandatoryZod.extend(teamOptionalZod.partial().shape);
export type TeamCreateInput = z.infer<typeof teamCreateInputZod>;

export const teamUpdateInputZod = teamMandatoryZod.extend(teamOptionalZod.shape).extend(teamAutoGeneratedZod.partial()).omit({
  apiSecretHash: true,
  rateLimitPerMinute: true,
  subscriptionAlertWebhookBearerToken: true,
});
export type TeamUpdateInput = z.infer<typeof teamUpdateInputZod>;

export const teamSelectAllZod = teamMandatoryZod.extend(teamOptionalZod.shape).extend(teamAutoGeneratedZod.shape).omit({
  apiSecretHash: true,
  subscriptionAlertWebhookBearerToken: true,
});
export type TeamSelectAll = z.infer<typeof teamSelectAllZod>;

export const teamGetByIdInputZod = z.object({
  teamId: z.uuid(),
});