import z from 'zod';
import { zText, zTimestamps } from './zod_utils.js';

const technicalReportMandatoryZod = z.object({
	serviceOrderId: z.string().uuid(),
	diagnostico: zText(),
	servicosExecutados: zText(),
});

const technicalReportOptionalZod = z.object({
	observacoes: zText().nullable(),
	assinadoTecnico: z.boolean(),
	assinadoCliente: z.boolean(),
});

const technicalReportAutoGeneratedZod = z.object({
	reportId: z.string().uuid(),
});

export const technicalReportCreateInputZod = technicalReportMandatoryZod.extend(
	technicalReportOptionalZod.partial().shape,
);

export const technicalReportUpdateInputZod = technicalReportMandatoryZod
	.extend(technicalReportOptionalZod.shape)
	.extend(technicalReportAutoGeneratedZod.shape)
	.partial()
	.required({ reportId: true });

export const technicalReportSelectAllZod = technicalReportMandatoryZod
	.extend(technicalReportOptionalZod.shape)
	.extend(technicalReportAutoGeneratedZod.shape)
	.extend(zTimestamps);

export const technicalReportGetByIdZod = z.object({ reportId: z.string().uuid() });
export const technicalReportByServiceOrderZod = z.object({ serviceOrderId: z.string().uuid() });

export type TechnicalReportCreateInput = z.infer<typeof technicalReportCreateInputZod>;
export type TechnicalReportUpdateInput = z.infer<typeof technicalReportUpdateInputZod>;
export type TechnicalReportSelectAll = z.infer<typeof technicalReportSelectAllZod>;
export type TechnicalReportGetById = z.infer<typeof technicalReportGetByIdZod>;
