import z from "zod";
import { zTimestamps, zVarchar, zText } from "./zod_utils.js";

const unitMandatoryZod = z.object({
	clienteId: z.uuid(),
	nome: zVarchar(1, 255),
});

const unitOptionalZod = z.object({
	descricao: zText().nullable(),
	endereco: zVarchar(0, 255).nullable(),
	cidade: zVarchar(0, 100).nullable(),
	estado: zVarchar(0, 2).nullable(),
	responsavelId: z.uuid().nullable(),
	ativa: z.boolean(),
});

const unitAutoGeneratedZod = z.object({
	unitId: z.uuid(),
});

export const unitCreateInputZod = unitMandatoryZod.extend(unitOptionalZod.partial().shape);
export const unitUpdateInputZod = unitMandatoryZod
	.extend(unitOptionalZod.shape)
	.extend(unitAutoGeneratedZod.shape)
	.partial()
	.required({ unitId: true });
export const unitSelectAllZod = unitMandatoryZod
	.extend(unitOptionalZod.shape)
	.extend(unitAutoGeneratedZod.shape)
	.extend(zTimestamps);

export const unitGetByIdZod = z.object({ unitId: z.uuid() });
export const unitsByClientZod = z.object({ clienteId: z.uuid() });

export type UnitCreateInput = z.infer<typeof unitCreateInputZod>;
export type UnitUpdateInput = z.infer<typeof unitUpdateInputZod>;
export type UnitSelectAll = z.infer<typeof unitSelectAllZod>;
