import z from 'zod';
import { userRoleZod } from './crm_enums.zod.js';

const userRoleMandatoryZod = z.object({
	userId: z.string().uuid(),
	role: userRoleZod,
});

const userRoleOptionalZod = z.object({
	assignedByUserId: z.string().uuid().nullable(),
});

const userRoleAutoGeneratedZod = z.object({
	userRoleId: z.string().uuid(),
	assignedAt: z.string(),
});

export const userRoleCreateZod = userRoleMandatoryZod.extend(userRoleOptionalZod.partial().shape);

export const userRoleSelectAllZod = userRoleMandatoryZod
	.extend(userRoleOptionalZod.shape)
	.extend(userRoleAutoGeneratedZod.shape);

export const listUserRoleFilterZod = z.object({
	userId: z.string().uuid().optional(),
	role: userRoleZod.optional(),
});

export const userRoleAssignZod = z.object({
	userId: z.string().uuid(),
	role: userRoleZod,
});

export const userRoleRevokeZod = z.object({
	userId: z.string().uuid(),
	role: userRoleZod,
});

export type UserRoleSelectAll = z.infer<typeof userRoleSelectAllZod>;
export type ListUserRoleFilter = z.infer<typeof listUserRoleFilterZod>;
export type UserRoleCreate = z.infer<typeof userRoleCreateZod>;
