import z from "zod";
import { zString, zTimestamps } from "./zod_utils.js";

export const userMandatoryZod = z.object({
  email: z.email(),
});

const userAutoGeneratedZod = z.object({
  userId: z.uuid(),
});

export const userOptionalZod = z.object({
  displayPicture: z.url().nullable(),
  name: zString.nullable(),
});

export const userCreateInputZod = userMandatoryZod.extend(userOptionalZod.partial().shape);
export type UserCreateInput = z.infer<typeof userCreateInputZod>;

export const userUpdateInputZod = userMandatoryZod.extend(userOptionalZod.shape).extend(zTimestamps).partial();
export type UserUpdateInput = z.infer<typeof userUpdateInputZod>;

export const userSelectAllZod = userMandatoryZod.extend(userOptionalZod.shape).extend(zTimestamps).extend(userAutoGeneratedZod.shape);
export type UserSelectAll = z.infer<typeof userSelectAllZod>;

export const userGetByIdInputZod = userAutoGeneratedZod;
export type UserGetByIdInput = z.infer<typeof userGetByIdInputZod>;