import z from "zod";
import { apiProductSkuZod, webhookStatusZod } from "./enums.zod.js";
import { zSmallint, zString, zTimeEpoch, zTimestamps } from "./zod_utils.js";

const webhookCallQueueAutoGeneratedZod = z.object({
  webhookCallQueueId: z.ulid(),
});

const webhookCallQueueMandatoryZod = z.object({
  teamId: z.uuid(),
  webhookUrl: z.url(),
  payload: z.json(),
  status: webhookStatusZod,
  attempts: zSmallint().positive().default(0),
  maxAttempts: zSmallint().positive().default(3),
  scheduledFor: zTimeEpoch,
  subscription_id: z.ulid(),
});

const webhookCallQueueOptionalZod = z.object({
  lastAttemptAt: zTimeEpoch.nullable(),
  sentAt: zTimeEpoch.nullable(),
  errorMessage: zString.nullable(),
});

export const webhookCallQueueCreateInputZod = webhookCallQueueMandatoryZod.extend(webhookCallQueueOptionalZod.partial().shape);
export type WebhookCallQueueCreateInput = z.infer<typeof webhookCallQueueCreateInputZod>;

export const webhookCallQueueUpdateInputZod = webhookCallQueueMandatoryZod.extend(webhookCallQueueOptionalZod.shape).extend(zTimestamps).partial();
export type WebhookCallQueueUpdateInput = z.infer<typeof webhookCallQueueUpdateInputZod>;

export const webhookCallQueueSelectAllZod = webhookCallQueueMandatoryZod.extend(webhookCallQueueOptionalZod.shape).extend(zTimestamps).extend(webhookCallQueueAutoGeneratedZod.shape);
export type WebhookCallQueueSelectAll = z.infer<typeof webhookCallQueueSelectAllZod>;

export const webhookCallQueueGetByIdInputZod = z.object({
  webhookCallQueueId: z.string(),
});

// Subscription Alert Webhook Payload Schema
export const subscriptionAlertWebhookPayloadZod = z.object({
  event: z.literal("subscription.usage_alert"),
  subscriptionId: z.ulid(),
  teamId: z.uuid(),
  apiProductSku: apiProductSkuZod,
  requestsConsumed: zSmallint(0),
  maxRequests: zSmallint(1),
  usagePercent: zSmallint(0, 100),
  timestamp: zTimeEpoch,
});

export type SubscriptionAlertWebhookPayload = z.infer<typeof subscriptionAlertWebhookPayloadZod>;