name: Tests

on:
  push:
    branches:
      - 'feature/**'
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: self-hosted
    container:
      image: node:22
      options: --network host
    name: Unit Tests

    steps:
      - name: Checkout monorepo
        run: |
          git clone --depth=1 http://127.0.0.1:3300/will-zappro/monorepo.git /home/node/monorepo
          cd /home/node/monorepo
          git fetch --depth=1 origin main

      - name: Configure Git
        run: |
          git config --global user.email "hermes@zappro.site"
          git config --global user.name "Hermes Agent"

      - name: Install dependencies
        working-directory: /home/node/monorepo
        run: pnpm install --frozen-lockfile

      - name: Run unit tests
        working-directory: /home/node/monorepo
        run: pnpm turbo test
