server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
    location /auth/callback {
        try_files /auth-callback.html =404;
    }
}
