#!/usr/bin/env python3
"""
HVAC Missing Manuals — Gap Finder (SPEC-401)
============================================
Cruza modelos Inverter homologados no Brasil (INMETRO/PBE) com os manuais
já indexados no Qdrant e gera um relatório priorizado de lacunas.

Uso:
    python3 hvac_missing_manuals.py
    python3 hvac_missing_manuals.py --dry-run
    python3 hvac_missing_manuals.py --brand LG
    python3 hvac_missing_manuals.py --output /srv/data/hvac-rag/reports/missing.md

Saída:
    missing_manuals_report.md — relatório de manuais faltantes por marca

Refs: SPEC-401 §3 | hvac_normalize_inmetro_catalog.py | hvac_qdrant_query.py
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from collections import defaultdict
from datetime import datetime
from pathlib import Path

import requests

# ── Config ────────────────────────────────────────────────────────────────────
QDRANT_URL = os.environ.get("QDRANT_URL", "http://127.0.0.1:6333")
QDRANT_API_KEY = os.environ.get("QDRANT_API_KEY", "")
COLLECTION_NAME = os.environ.get("HVAC_COLLECTION", "hvac_manuals_v1")

CATALOG_JSONL = Path(os.environ.get(
    "HVAC_INMETRO_CATALOG",
    "/srv/data/hvac-rag/catalog/inmetro_ac_br_models.jsonl"
))

REPORTS_DIR = Path(os.environ.get(
    "HVAC_REPORTS_DIR",
    "/srv/data/hvac-rag/reports"
))

# Brands tracked (SPEC-401 §7)
TRACKED_BRANDS = {
    "lg", "samsung", "daikin", "carrier", "springer", "midea",
    "gree", "fujitsu", "hitachi", "komeco", "elgin", "agratto",
    "trane", "vrv", "vrf",
}

# ── Inverter filter (SPEC-401 §2) ─────────────────────────────────────────────
INVERTER_TECHNOLOGY_VALUES = {"inverter", "dual inverter", "vrf", "vrv", "multi-split"}

BLACKLISTED_EQUIP_TYPES = {"janela", "portatil"}


def _qdrant_headers() -> dict:
    h = {"Content-Type": "application/json"}
    if QDRANT_API_KEY:
        h["Authorization"] = f"Bearer {QDRANT_API_KEY}"
    return h


# ── Qdrant: list all indexed brands/models ────────────────────────────────────
def get_indexed_models(brand_filter: str | None = None) -> set[str]:
    """
    Scroll through Qdrant collection and collect all (brand, model) pairs
    already indexed. Returns a set of lowercase keys: "brand::model_family".
    """
    indexed: set[str] = set()
    offset = None
    limit = 100

    scroll_filter = {}
    if brand_filter:
        scroll_filter = {
            "filter": {
                "must": [{"key": "brand", "match": {"value": brand_filter.title()}}]
            }
        }

    try:
        while True:
            payload: dict = {"limit": limit, "with_payload": True}
            if offset:
                payload["offset"] = offset
            if scroll_filter:
                payload.update(scroll_filter)

            r = requests.post(
                f"{QDRANT_URL}/collections/{COLLECTION_NAME}/points/scroll",
                headers=_qdrant_headers(),
                json=payload,
                timeout=30,
            )
            if r.status_code != 200:
                print(f"⚠️  Qdrant scroll error {r.status_code}: {r.text[:200]}", file=sys.stderr)
                break

            data = r.json().get("result", {})
            points = data.get("points", [])
            next_offset = data.get("next_page_offset")

            for point in points:
                p = point.get("payload", {})
                brand = (p.get("brand") or "").lower().strip()
                model_family = (p.get("model_family") or p.get("model") or "").lower().strip()
                if brand and model_family:
                    indexed.add(f"{brand}::{model_family}")

            if not next_offset or not points:
                break
            offset = next_offset

    except requests.ConnectionError:
        print("❌ Não foi possível conectar ao Qdrant. Verifique QDRANT_URL.", file=sys.stderr)

    return indexed


# ── INMETRO catalog loader ────────────────────────────────────────────────────
def load_inmetro_catalog(brand_filter: str | None = None) -> list[dict]:
    """
    Loads JSONL catalog generated by hvac_normalize_inmetro_catalog.py.
    Filters: inverter technology only, tracked brands only.
    """
    if not CATALOG_JSONL.exists():
        print(f"⚠️  Catálogo INMETRO não encontrado: {CATALOG_JSONL}", file=sys.stderr)
        print("   Execute hvac_normalize_inmetro_catalog.py primeiro.", file=sys.stderr)
        return []

    models: list[dict] = []
    with CATALOG_JSONL.open(encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                rec = json.loads(line)
            except json.JSONDecodeError:
                continue

            brand = (rec.get("brand") or "").lower().strip()
            technology = (rec.get("technology") or "").lower().strip()
            equip_type = (rec.get("equipment_type") or "").lower().strip()

            # Apply inverter whitelist (SPEC-401 §2.1)
            if technology not in INVERTER_TECHNOLOGY_VALUES:
                continue

            # Apply conventional blacklist (SPEC-401 §2.2)
            if equip_type in BLACKLISTED_EQUIP_TYPES:
                continue

            # Brand filter
            if brand not in TRACKED_BRANDS:
                continue
            if brand_filter and brand != brand_filter.lower():
                continue

            models.append(rec)

    return models


# ── Report generator ──────────────────────────────────────────────────────────
def generate_report(
    catalog: list[dict],
    indexed: set[str],
    dry_run: bool = False,
    output_path: Path | None = None,
) -> str:
    """
    Diffs the INMETRO catalog against the Qdrant index.
    Returns a Markdown report of missing manuals.
    """
    missing_by_brand: dict[str, list[dict]] = defaultdict(list)
    covered_by_brand: dict[str, int] = defaultdict(int)

    for rec in catalog:
        brand = (rec.get("brand") or "").lower().strip()
        model_family = (rec.get("model_family") or rec.get("model") or "").lower().strip()
        key = f"{brand}::{model_family}"

        if key in indexed:
            covered_by_brand[brand] += 1
        else:
            missing_by_brand[brand].append(rec)

    total_missing = sum(len(v) for v in missing_by_brand.values())
    total_covered = sum(covered_by_brand.values())
    total = total_missing + total_covered
    coverage_pct = round(100 * total_covered / total, 1) if total > 0 else 0.0

    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    lines: list[str] = [
        f"# 📋 Relatório de Manuais Faltantes — HVAC Inverter BR",
        f"",
        f"**Gerado:** {now}  ",
        f"**Coleção Qdrant:** `{COLLECTION_NAME}`  ",
        f"**Catálogo:** `{CATALOG_JSONL}`  ",
        f"",
        f"## Resumo",
        f"",
        f"| Métrica | Valor |",
        f"|---|---|",
        f"| Total de modelos Inverter (INMETRO) | {total} |",
        f"| Modelos com manual indexado | {total_covered} ✅ |",
        f"| **Modelos SEM manual** | **{total_missing} ❌** |",
        f"| Cobertura atual | **{coverage_pct}%** |",
        f"",
    ]

    if total_missing == 0:
        lines.append("🎉 **Base completa! Todos os modelos possuem manual indexado.**")
        return "\n".join(lines)

    lines.append("## Lacunas por Marca (Ordenado por Prioridade)")
    lines.append("")

    # Sort by missing count desc
    sorted_brands = sorted(missing_by_brand.items(), key=lambda x: len(x[1]), reverse=True)

    for brand, missing in sorted_brands:
        covered = covered_by_brand.get(brand, 0)
        brand_total = len(missing) + covered
        brand_pct = round(100 * covered / brand_total, 1) if brand_total > 0 else 0.0
        brand_label = brand.upper()

        lines.append(f"### {brand_label} — {len(missing)} modelos sem manual ({brand_pct}% coberto)")
        lines.append("")

        for rec in sorted(missing, key=lambda x: x.get("model", "")):
            model = rec.get("model") or "N/A"
            model_family = rec.get("model_family") or ""
            capacity = rec.get("capacity_btu") or rec.get("capacity") or "?"
            refrigerant = rec.get("refrigerant") or "?"
            equip_type = rec.get("equipment_type") or "split"
            inmetro_id = rec.get("inmetro_id") or ""

            cap_str = f"{capacity} BTU/h" if isinstance(capacity, (int, float)) else str(capacity)
            family_str = f" ({model_family})" if model_family and model_family.lower() != model.lower() else ""

            line = f"- `{model}`{family_str} — {cap_str} | {equip_type} | {refrigerant}"
            if inmetro_id:
                line += f" | INMETRO: {inmetro_id}"
            lines.append(line)

        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("## Como Obter os Manuais Faltantes")
    lines.append("")
    lines.append("1. Acesse o portal de suporte técnico da fabricante (uso de credencial profissional)")
    lines.append("2. Procure por 'Service Manual' ou 'Manual de Serviço Técnico'")
    lines.append("3. Após download, execute o pipeline de ingestão:")
    lines.append("")
    lines.append("```bash")
    lines.append("python3 scripts/hvac-rag/hvac_rag_pipe.py \\")
    lines.append("  --pdf /caminho/para/manual.pdf \\")
    lines.append("  --brand <MARCA> \\")
    lines.append("  --index")
    lines.append("```")
    lines.append("")

    return "\n".join(lines)


# ── CLI ───────────────────────────────────────────────────────────────────────
def main() -> None:
    parser = argparse.ArgumentParser(
        description="HVAC Missing Manuals Gap Finder (SPEC-401 §3)"
    )
    parser.add_argument("--dry-run", action="store_true", help="Exibe relatório sem salvar arquivo")
    parser.add_argument("--brand", type=str, help="Filtrar por marca específica (ex: LG)")
    parser.add_argument("--output", type=str, help="Caminho do arquivo de saída .md")
    args = parser.parse_args()

    brand_filter = args.brand.strip() if args.brand else None
    output_path = Path(args.output) if args.output else REPORTS_DIR / "missing_manuals_report.md"

    print("🔍 HVAC Missing Manuals — Gap Finder")
    print(f"   Coleção Qdrant : {COLLECTION_NAME}")
    print(f"   Catálogo INMETRO: {CATALOG_JSONL}")
    if brand_filter:
        print(f"   Filtro de marca : {brand_filter.upper()}")
    print()

    # 1. Load INMETRO catalog
    print("📥 Carregando catálogo INMETRO...")
    catalog = load_inmetro_catalog(brand_filter)
    print(f"   {len(catalog)} modelos Inverter encontrados no catálogo")

    if not catalog:
        print("⚠️  Catálogo vazio. Verifique o arquivo JSONL e execute hvac_normalize_inmetro_catalog.py.")
        sys.exit(0)

    # 2. Query Qdrant for indexed models
    print("🔎 Consultando Qdrant para modelos indexados...")
    indexed = get_indexed_models(brand_filter)
    print(f"   {len(indexed)} entradas encontradas no Qdrant")

    # 3. Generate report
    print("📊 Gerando relatório de lacunas...")
    report_md = generate_report(catalog, indexed, dry_run=args.dry_run, output_path=output_path)

    if args.dry_run:
        print()
        print("─" * 60)
        print(report_md)
        print("─" * 60)
        print("\n[dry-run] Arquivo NÃO foi salvo.")
    else:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(report_md, encoding="utf-8")
        print(f"\n✅ Relatório salvo em: {output_path}")
        # Print summary lines only
        for line in report_md.splitlines()[:20]:
            print(line)


if __name__ == "__main__":
    main()
