package parser

import (
	"strings"
)

// ErrorCode represents an HVAC error code with diagnostic information.
type ErrorCode struct {
	ID                string   `json:"id"`                 // Unique identifier (e.g., "LG-E1")
	Brand             string   `json:"brand"`               // LG, Samsung, Springer, Daikin, etc.
	Code              string   `json:"code"`               // Display code (e.g., "E1", "CH01")
	Name              string   `json:"name"`                // Short name (e.g., "Indoor Fan Motor Error")
	Subsystem         string   `json:"subsystem"`           // indoor_unit, outdoor_unit, compressor, etc.
	Severity          string   `json:"severity"`            // critical, warning, info
	Description      string   `json:"description"`          // What the error means
	RootCauses        []string `json:"root_causes"`         // Possible causes
	DiagnosticSteps   []string `json:"diagnostic_steps"`    // How to diagnose
	TestPoints        []string `json:"test_points"`         // What to measure
	ResetProcedure    []string `json:"reset_procedure"`      // How to reset
	PartsLikelyNeeded []string `json:"parts_likely_needed"` // Common replacement parts
	RelatedCodes      []string `json:"related_codes"`       // Often accompany or confused with
}

// BrandErrorCodes maps brand names to their error codes
var BrandErrorCodes = map[string][]ErrorCode{
	"Springer/Midea": {
		{Code: "E0", Name: "Indoor Fan Motor Error", Brand: "Springer/Midea", Subsystem: "indoor", Severity: "critical", Description: "Indoor unit fan motor failure or RPM out of range", RootCauses: []string{"Motor winding open/shorted", "Fan blade locked", "Capacitor failed", "PCB failed"}, DiagnosticSteps: []string{"Check motor resistance (normal 10-50Ω)", "Verify fan blade rotates freely", "Test capacitor (normal 3-10μF)", "Check PCB output voltage"}, TestPoints: []string{"Motor resistance: 10-50Ω", "Capacitor: 3-10μF"}, ResetProcedure: []string{"Turn off power", "Wait 30 seconds", "Turn on power", "Press reset button if available"}, PartsLikelyNeeded: []string{"Indoor fan motor", "Capacitor", "PCB"}, RelatedCodes: []string{"E1", "E6"}},
		{Code: "E1", Name: "Indoor/Outdoor Communication Error", Brand: "Springer/Midea", Subsystem: "communication", Severity: "critical", Description: "Communication failure between indoor and outdoor units", RootCauses: []string{"Wire cut/loose", "Connector corrosion", "PCB failure", "Noise interference"}, DiagnosticSteps: []string{"Check interconnection wiring", "Verify connector seating", "Test communication voltage (3.3V DC)", "Check for water damage"}, TestPoints: []string{"Communication voltage: 3.3V DC", "Wire continuity: <1Ω"}, ResetProcedure: []string{"Turn off power", "Check all connections", "Turn on power", "If persists, replace PCB"}, PartsLikelyNeeded: []string{"Indoor PCB", "Outdoor PCB", " interconnect wiring"}, RelatedCodes: []string{"E0", "E2"}},
		{Code: "E2", Name: "Outdoor Fan Motor Error", Brand: "Springer/Midea", Subsystem: "outdoor", Severity: "critical", Description: "Outdoor unit fan motor failure or RPM out of range", RootCauses: []string{"Motor winding failed", "Fan blade locked", "Capacitor failed", "Outdoor PCB failed"}, DiagnosticSteps: []string{"Check motor resistance", "Verify fan rotation", "Test capacitor", "Check PCB output"}, TestPoints: []string{"Motor resistance: 10-50Ω", "Capacitor: 5-15μF"}, ResetProcedure: []string{"Turn off power", "Wait 30 seconds", "Turn on power"}, PartsLikelyNeeded: []string{"Outdoor fan motor", "Capacitor", "Outdoor PCB"}, RelatedCodes: []string{"E0", "E3"}},
		{Code: "E5", Name: "Overload Protection", Brand: "Springer/Midea", Subsystem: "compressor", Severity: "critical", Description: "Compressor overload protection activated", RootCauses: []string{"Dirty condenser", "Refrigerant overcharge", "Compressor failing", "Fan not running"}, DiagnosticSteps: []string{"Clean condenser fins", "Check refrigerant pressure", "Test compressor amp draw", "Verify outdoor fan"}, TestPoints: []string{"Compressor amp: check nameplate", "Discharge pressure: 250-350 PSI"}, ResetProcedure: []string{"Turn off power", "Clean condenser", "Wait 3 minutes", "Turn on power"}, PartsLikelyNeeded: []string{"Compressor overload", "Contactor"}, RelatedCodes: []string{"E6", "E8"}},
		{Code: "E6", Name: "Compressor Failure", Brand: "Springer/Midea", Subsystem: "compressor", Severity: "critical", Description: "Compressor not running or locked", RootCauses: []string{"Winding failed", "Valve leakage", "Electrical failure", "Mechanical seizure"}, DiagnosticSteps: []string{"Test compressor winding resistance", "Check for valve hiss", "Verify electrical supply", "Check amp draw"}, TestPoints: []string{"U-V: 1-5Ω", "V-W: 1-5Ω", "W-U: 1-5Ω"}, ResetProcedure: []string{"Turn off power", "Call service technician", "Do not attempt restart"}, PartsLikelyNeeded: []string{"Compressor", "Run capacitor"}, RelatedCodes: []string{"E5", "E8"}},
		{Code: "E8", Name: "High Pressure Protection", Brand: "Springer/Midea", Subsystem: "outdoor", Severity: "critical", Description: "High pressure switch activated", RootCauses: []string{"Dirty condenser", "Fan not working", "Refrigerant overcharge", "Blocked airflow"}, DiagnosticSteps: []string{"Clean condenser", "Verify fan operation", "Check pressure switch", "Verify refrigerant charge"}, TestPoints: []string{"High pressure switch: continuity when open", "Discharge pressure: 250-350 PSI"}, ResetProcedure: []string{"Turn off power", "Clean condenser and vents", "Wait 5 minutes", "Turn on power"}, PartsLikelyNeeded: []string{"High pressure switch", "Condenser fan motor"}, RelatedCodes: []string{"E5", "E6"}},
	},
	"LG": {
		{Code: "E1", Name: "Remote Control Error", Brand: "LG", Subsystem: "indoor", Severity: "info", Description: "Indoor unit does not receive remote control signal", RootCauses: []string{"Dead batteries", "Remote sensor damaged", "IR signal blocked", "Main PCB not receiving"}, DiagnosticSteps: []string{"Replace batteries", "Test with another remote", "Check sensor window", "Bypass remote to test"}, TestPoints: []string{"Remote battery: 1.5V each"}, ResetProcedure: []string{"Replace batteries", "Point remote directly at unit", "Press any button"}, PartsLikelyNeeded: []string{"Remote control", "Indoor PCB"}, RelatedCodes: []string{"E4"}},
		{Code: "CH01", Name: "Indoor Fan Motor Error", Brand: "LG", Subsystem: "indoor", Severity: "critical", Description: "Indoor DC fan motor lock or communication error", RootCauses: []string{"Motor failed", "Fan locked", "PCB failed", "Hall sensor failed"}, DiagnosticSteps: []string{"Check motor connector", "Test motor resistance", "Verify 12V power supply", "Check hall sensor"}, TestPoints: []string{"Motor voltage: 12V DC", "Hall sensor: 5V signal"}, ResetProcedure: []string{"Turn off power", "Clean fan blade", "Turn on power", "If persists, replace motor"}, PartsLikelyNeeded: []string{"Indoor fan motor", "Indoor PCB"}, RelatedCodes: []string{"CH02", "CH10"}},
		{Code: "CH02", Name: "Outdoor Fan Motor Error", Brand: "LG", Subsystem: "outdoor", Severity: "critical", Description: "Outdoor DC fan motor error or lock", RootCauses: []string{"Motor winding shorted", "Fan locked", "Fan capacitor failed", "Outdoor PCB failed"}, DiagnosticSteps: []string{"Check motor connector", "Test motor resistance", "Test capacitor", "Check PCB output"}, TestPoints: []string{"Motor resistance: 10-50Ω", "Capacitor: 3-10μF"}, ResetProcedure: []string{"Turn off power", "Wait 30 seconds", "Turn on power"}, PartsLikelyNeeded: []string{"Outdoor fan motor", "Fan capacitor", "Outdoor PCB"}, RelatedCodes: []string{"CH01", "CH10"}},
		{Code: "CH10", Name: "Compressor Error", Brand: "LG", Subsystem: "compressor", Severity: "critical", Description: "Compressor not running or overcurrent detected", RootCauses: []string{"Compressor failed", "Contactor failed", "Outdoor PCB failed", "Refrigerant issue"}, DiagnosticSteps: []string{"Test compressor winding", "Check contactor", "Verify amp draw", "Check refrigerant"}, TestPoints: []string{"Compressor U-V: 1-5Ω", "Contactor coil: 100-200Ω"}, ResetProcedure: []string{"Turn off power", "Wait 3 minutes", "Turn on power", "If persists, call service"}, PartsLikelyNeeded: []string{"Compressor", "Contactor", "Outdoor PCB"}, RelatedCodes: []string{"CH19", "E4"}},
		{Code: "CH19", Name: "Inverter Compressor Error", Brand: "LG", Subsystem: "compressor", Severity: "critical", Description: "Inverter compressor module error", RootCauses: []string{"IPM failure", "Compressor locked", "DC link capacitor failed", "Software issue"}, DiagnosticSteps: []string{"Check IPM temperature", "Test DC link voltage", "Verify compressor winding", "Reset via PCB"}, TestPoints: []string{"DC link voltage: 300-400V DC", "IPM temp: <70°C"}, ResetProcedure: []string{"Turn off power", "Wait 5 minutes", "Turn on power", "If persists, replace outdoor PCB"}, PartsLikelyNeeded: []string{"Outdoor PCB", "Compressor"}, RelatedCodes: []string{"CH10", "E4"}},
		{Code: "E4", Name: "Indoor Temperature Sensor Error", Brand: "LG", Subsystem: "indoor", Severity: "warning", Description: "Indoor room temperature sensor (thermistor) error", RootCauses: []string{"Sensor open/shorted", "Connector loose", "PCB failed"}, DiagnosticSteps: []string{"Test sensor resistance at room temp (25°C = 10kΩ)", "Check connector", "Bypass sensor to test"}, TestPoints: []string{"Sensor resistance: 10kΩ at 25°C"}, ResetProcedure: []string{"Turn off power", "Reconnect sensor", "Turn on power"}, PartsLikelyNeeded: []string{"Room temperature sensor"}, RelatedCodes: []string{"E1", "CH01"}},
	},
	"Samsung": {
		{Code: "E1", Name: "Communication Error", Brand: "Samsung", Subsystem: "communication", Severity: "critical", Description: "Indoor/outdoor communication failure", RootCauses: []string{"Wire broken", "Connector loose", "PCB damaged", "Noise"}, DiagnosticSteps: []string{"Check interconnection wires", "Verify connectors", "Test communication voltage", "Check PCB"}, TestPoints: []string{"Communication voltage: 12V DC"}, ResetProcedure: []string{"Turn off power", "Check all connections", "Turn on power"}, PartsLikelyNeeded: []string{"Indoor PCB", "Outdoor PCB", " interconnect wiring"}, RelatedCodes: []string{"E4", "E101"}},
		{Code: "E4", Name: "Temperature Sensor Error", Brand: "Samsung", Subsystem: "indoor", Severity: "warning", Description: "Indoor temperature sensor fault", RootCauses: []string{"Sensor failed", "Connector loose", "PCB failed"}, DiagnosticSteps: []string{"Test sensor resistance", "Check connector", "Verify PCB input"}, TestPoints: []string{"Sensor: 10kΩ at 25°C"}, ResetProcedure: []string{"Reconnect sensor", "Turn off/on power"}, PartsLikelyNeeded: []string{"Temperature sensor"}, RelatedCodes: []string{"E1", "E103"}},
		{Code: "E101", Name: "Indoor Fan Motor Error", Brand: "Samsung", Subsystem: "indoor", Severity: "critical", Description: "Indoor DC fan motor error", RootCauses: []string{"Motor failed", "Hall sensor failed", "PCB failed", "Blade locked"}, DiagnosticSteps: []string{"Check motor connector", "Test motor winding", "Test hall sensor", "Check voltage"}, TestPoints: []string{"Motor voltage: 12V DC"}, ResetProcedure: []string{"Turn off power", "Clean fan", "Turn on power"}, PartsLikelyNeeded: []string{"Indoor fan motor", "Indoor PCB"}, RelatedCodes: []string{"E1", "E102"}},
		{Code: "E102", Name: "Outdoor Fan Motor Error", Brand: "Samsung", Subsystem: "outdoor", Severity: "critical", Description: "Outdoor fan motor error", RootCauses: []string{"Motor failed", "Capacitor failed", "PCB failed", "Blade locked"}, DiagnosticSteps: []string{"Check motor resistance", "Test capacitor", "Verify rotation"}, TestPoints: []string{"Motor resistance: 10-50Ω"}, ResetProcedure: []string{"Turn off power", "Clean fan", "Turn on power"}, PartsLikelyNeeded: []string{"Outdoor fan motor", "Capacitor"}, RelatedCodes: []string{"E101", "E103"}},
		{Code: "E103", Name: "Compressor Error", Brand: "Samsung", Subsystem: "compressor", Severity: "critical", Description: "Compressor system error", RootCauses: []string{"Compressor locked", "IPM failed", "PCB failed"}, DiagnosticSteps: []string{"Test compressor winding", "Check IPM", "Verify DC link voltage"}, TestPoints: []string{"DC link: 300-400V DC"}, ResetProcedure: []string{"Turn off power", "Wait 3 minutes", "Turn on power"}, PartsLikelyNeeded: []string{"Compressor", "Outdoor PCB"}, RelatedCodes: []string{"E101", "E102"}},
	},
	"Daikin": {
		{Code: "A1", Name: "Indoor PCB Error", Brand: "Daikin", Subsystem: "indoor", Severity: "critical", Description: "Indoor PCB malfunction", RootCauses: []string{"PCB failed", "Power supply issue", "Capacitor leak"}, DiagnosticSteps: []string{"Visual inspection", "Check power supply", "Test outputs"}, TestPoints: []string{"Power supply: 12V, 5V DC"}, ResetProcedure: []string{"Turn off power", "Wait 30 seconds", "Turn on power"}, PartsLikelyNeeded: []string{"Indoor PCB"}, RelatedCodes: []string{"A5", "E1"}},
		{Code: "A5", Name: "Indoor Fan Motor Error", Brand: "Daikin", Subsystem: "indoor", Severity: "critical", Description: "Indoor fan motor error", RootCauses: []string{"Motor failed", "Capacitor failed", "PCB failed"}, DiagnosticSteps: []string{"Check motor connector", "Test motor winding", "Test capacitor"}, TestPoints: []string{"Motor resistance: 10-50Ω"}, ResetProcedure: []string{"Turn off power", "Wait 30 seconds", "Turn on power"}, PartsLikelyNeeded: []string{"Indoor fan motor", "Capacitor"}, RelatedCodes: []string{"A1", "A6"}},
		{Code: "A6", Name: "Outdoor Fan Motor Error", Brand: "Daikin", Subsystem: "outdoor", Severity: "critical", Description: "Outdoor fan motor error", RootCauses: []string{"Motor failed", "Capacitor failed", "Fan locked"}, DiagnosticSteps: []string{"Check motor connector", "Test motor", "Test capacitor"}, TestPoints: []string{"Motor resistance: 10-50Ω"}, ResetProcedure: []string{"Turn off power", "Clean fan", "Turn on power"}, PartsLikelyNeeded: []string{"Outdoor fan motor", "Capacitor"}, RelatedCodes: []string{"A5", "C9"}},
		{Code: "C4", Name: "Indoor Suction Temperature Sensor Error", Brand: "Daikin", Subsystem: "indoor", Severity: "warning", Description: "Indoor suction temperature sensor fault", RootCauses: []string{"Sensor failed", "Connector loose"}, DiagnosticSteps: []string{"Test sensor resistance", "Check connector"}, TestPoints: []string{"Sensor: 10kΩ at 25°C"}, ResetProcedure: []string{"Reconnect sensor", "Turn off/on power"}, PartsLikelyNeeded: []string{"Suction temperature sensor"}, RelatedCodes: []string{"C9", "E1"}},
		{Code: "C9", Name: "Indoor Coil Temperature Sensor Error", Brand: "Daikin", Subsystem: "indoor", Severity: "warning", Description: "Indoor coil temperature sensor fault", RootCauses: []string{"Sensor failed", "Connector loose"}, DiagnosticSteps: []string{"Test sensor resistance", "Check connector"}, TestPoints: []string{"Sensor: 10kΩ at 25°C"}, ResetProcedure: []string{"Reconnect sensor", "Turn off/on power"}, PartsLikelyNeeded: []string{"Coil temperature sensor"}, RelatedCodes: []string{"C4", "E1"}},
		{Code: "E1", Name: "Remote Control Error", Brand: "Daikin", Subsystem: "indoor", Severity: "info", Description: "Remote control reception error", RootCauses: []string{"Dead batteries", "Remote sensor damaged"}, DiagnosticSteps: []string{"Replace batteries", "Test another remote"}, TestPoints: []string{"Battery: 1.5V each"}, ResetProcedure: []string{"Replace batteries"}, PartsLikelyNeeded: []string{"Remote control"}, RelatedCodes: []string{"C4"}},
		{Code: "E3", Name: "Outdoor Pressure Sensor Error", Brand: "Daikin", Subsystem: "outdoor", Severity: "warning", Description: "High pressure sensor fault", RootCauses: []string{"Sensor failed", "Wiring broken"}, DiagnosticSteps: []string{"Test sensor", "Check wiring"}, TestPoints: []string{"Pressure sensor: 0.5-4.5V output"}, ResetProcedure: []string{"Check connections", "Turn off/on power"}, PartsLikelyNeeded: []string{"Pressure sensor"}, RelatedCodes: []string{"E5", "A6"}},
		{Code: "E5", Name: "Overload Protection", Brand: "Daikin", Subsystem: "compressor", Severity: "critical", Description: "Compressor overload protection", RootCauses: []string{"Dirty condenser", "Low refrigerant", "Fan not working"}, DiagnosticSteps: []string{"Clean condenser", "Check refrigerant", "Verify fan"}, TestPoints: []string{"Discharge pressure: 250-350 PSI"}, ResetProcedure: []string{"Turn off power", "Clean condenser", "Turn on power"}, PartsLikelyNeeded: []string{"Overload protector"}, RelatedCodes: []string{"E3", "A6"}},
	},
	"Consul/Electrolux": {
		{Code: "E0", Name: "Indoor Fan Motor Error", Brand: "Consul/Electrolux", Subsystem: "indoor", Severity: "critical", Description: "Indoor fan motor error", RootCauses: []string{"Motor failed", "Capacitor failed", "PCB failed"}, DiagnosticSteps: []string{"Check motor", "Test capacitor", "Check voltage"}, TestPoints: []string{"Motor: 10-50Ω"}, ResetProcedure: []string{"Turn off power", "Wait 30s", "Turn on"}, PartsLikelyNeeded: []string{"Fan motor", "Capacitor"}, RelatedCodes: []string{"E1", "E8"}},
		{Code: "E1", Name: "Communication Error", Brand: "Consul/Electrolux", Subsystem: "communication", Severity: "critical", Description: "Indoor/outdoor communication error", RootCauses: []string{"Wire broken", "Connector loose"}, DiagnosticSteps: []string{"Check wiring", "Check connectors"}, TestPoints: []string{"Communication: 12V DC"}, ResetProcedure: []string{"Check connections", "Power cycle"}, PartsLikelyNeeded: []string{"Wiring harness"}, RelatedCodes: []string{"E0", "E2"}},
		{Code: "E2", Name: "Outdoor Fan Motor Error", Brand: "Consul/Electrolux", Subsystem: "outdoor", Severity: "critical", Description: "Outdoor fan motor error", RootCauses: []string{"Motor failed", "Capacitor failed"}, DiagnosticSteps: []string{"Check motor", "Test capacitor"}, TestPoints: []string{"Motor: 10-50Ω"}, ResetProcedure: []string{"Turn off power", "Clean fan", "Turn on"}, PartsLikelyNeeded: []string{"Fan motor", "Capacitor"}, RelatedCodes: []string{"E0", "E5"}},
		{Code: "E5", Name: "Overload Protection", Brand: "Consul/Electrolux", Subsystem: "compressor", Severity: "critical", Description: "Compressor overload protection", RootCauses: []string{"Dirty condenser", "Low refrigerant"}, DiagnosticSteps: []string{"Clean condenser", "Check refrigerant charge"}, TestPoints: []string{"Discharge pressure: 250-350 PSI"}, ResetProcedure: []string{"Turn off power", "Clean condenser", "Power cycle"}, PartsLikelyNeeded: []string{"Overload protector"}, RelatedCodes: []string{"E6", "E8"}},
		{Code: "E6", Name: "Compressor Error", Brand: "Consul/Electrolux", Subsystem: "compressor", Severity: "critical", Description: "Compressor not running", RootCauses: []string{"Compressor failed", "Contactor failed"}, DiagnosticSteps: []string{"Test compressor winding", "Check contactor"}, TestPoints: []string{"Compressor U-V: 1-5Ω"}, ResetProcedure: []string{"Call service"}, PartsLikelyNeeded: []string{"Compressor", "Contactor"}, RelatedCodes: []string{"E5", "E8"}},
		{Code: "E8", Name: "High Pressure Error", Brand: "Consul/Electrolux", Subsystem: "outdoor", Severity: "critical", Description: "High pressure protection", RootCauses: []string{"Dirty condenser", "Fan not working"}, DiagnosticSteps: []string{"Clean condenser", "Verify fan"}, TestPoints: []string{"HP switch continuity"}, ResetProcedure: []string{"Turn off power", "Clean", "Power cycle"}, PartsLikelyNeeded: []string{"HP switch", "Fan motor"}, RelatedCodes: []string{"E5", "E6"}},
	},
	"Gree": {
		{Code: "E1", Name: "High Pressure Protection", Brand: "Gree", Subsystem: "outdoor", Severity: "critical", Description: "High pressure switch activated", RootCauses: []string{"Dirty condenser", "Fan not working", "Blocked airflow"}, DiagnosticSteps: []string{"Clean condenser", "Verify fan", "Check HP switch"}, TestPoints: []string{"HP switch: open when triggered"}, ResetProcedure: []string{"Turn off power", "Clean condenser", "Wait 5 min", "Turn on"}, PartsLikelyNeeded: []string{"HP switch", "Condenser fan"}, RelatedCodes: []string{"E2", "F1"}},
		{Code: "E2", Name: "Indoor Frost Protection", Brand: "Gree", Subsystem: "indoor", Severity: "warning", Description: "Indoor coil frost detected - defrost cycle", RootCauses: []string{"Low airflow", "Low refrigerant", "Dirty filter"}, DiagnosticSteps: []string{"Check filter", "Verify fan", "Check refrigerant"}, TestPoints: []string{"Coil temp: <0°C when frost"}, ResetProcedure: []string{"Clean filter", "Wait for auto defrost"}, PartsLikelyNeeded: []string{"Air filter"}, RelatedCodes: []string{"E1", "E4"}},
		{Code: "E4", Name: "Indoor Coil Temperature Sensor Error", Brand: "Gree", Subsystem: "indoor", Severity: "warning", Description: "Indoor coil sensor fault", RootCauses: []string{"Sensor failed", "Connector loose"}, DiagnosticSteps: []string{"Test sensor resistance", "Check connector"}, TestPoints: []string{"Sensor: 10kΩ at 25°C"}, ResetProcedure: []string{"Reconnect sensor", "Power cycle"}, PartsLikelyNeeded: []string{"Temperature sensor"}, RelatedCodes: []string{"F1", "F2"}},
		{Code: "F1", Name: "Communication Error", Brand: "Gree", Subsystem: "communication", Severity: "critical", Description: "Indoor/outdoor communication error", RootCauses: []string{"Wire broken", "Connector loose"}, DiagnosticSteps: []string{"Check wiring", "Verify connectors"}, TestPoints: []string{"Communication: 12V DC"}, ResetProcedure: []string{"Check connections", "Power cycle"}, PartsLikelyNeeded: []string{"Wiring harness"}, RelatedCodes: []string{"E1", "E4"}},
		{Code: "F2", Name: "Outdoor Temperature Sensor Error", Brand: "Gree", Subsystem: "outdoor", Severity: "warning", Description: "Outdoor temperature sensor fault", RootCauses: []string{"Sensor failed", "Connector loose"}, DiagnosticSteps: []string{"Test sensor", "Check connector"}, TestPoints: []string{"Sensor: 10kΩ at 25°C"}, ResetProcedure: []string{"Reconnect sensor", "Power cycle"}, PartsLikelyNeeded: []string{"Temperature sensor"}, RelatedCodes: []string{"E4", "F3"}},
		{Code: "F3", Name: "Compressor Discharge Temperature Error", Brand: "Gree", Subsystem: "compressor", Severity: "critical", Description: "Compressor discharge temp too high", RootCauses: []string{"Low refrigerant", "Compressor failing", "Restricted airflow"}, DiagnosticSteps: []string{"Check refrigerant", "Test discharge temp"}, TestPoints: []string{"Discharge temp: <100°C normal"}, ResetProcedure: []string{"Turn off power", "Call service"}, PartsLikelyNeeded: []string{"Compressor"}, RelatedCodes: []string{"F2", "E1"}},
	},
	"Fujitsu": {
		{Code: "AL", Name: "Indoor Fan Motor Error", Brand: "Fujitsu", Subsystem: "indoor", Severity: "critical", Description: "Indoor DC fan motor error", RootCauses: []string{"Motor failed", "PCB failed", "Hall sensor failed"}, DiagnosticSteps: []string{"Check motor connector", "Test motor", "Check hall sensor"}, TestPoints: []string{"Motor voltage: 12V DC"}, ResetProcedure: []string{"Turn off power", "Clean fan", "Turn on"}, PartsLikelyNeeded: []string{"Indoor fan motor"}, RelatedCodes: []string{"E1", "E5"}},
		{Code: "E1", Name: "Indoor/Outdoor Communication Error", Brand: "Fujitsu", Subsystem: "communication", Severity: "critical", Description: "Communication failure", RootCauses: []string{"Wire broken", "Connector loose"}, DiagnosticSteps: []string{"Check wiring", "Verify connectors"}, TestPoints: []string{"Communication: 12V DC"}, ResetProcedure: []string{"Check connections", "Power cycle"}, PartsLikelyNeeded: []string{"Wiring harness"}, RelatedCodes: []string{"AL", "E5"}},
		{Code: "E5", Name: "Compressor Overload", Brand: "Fujitsu", Subsystem: "compressor", Severity: "critical", Description: "Compressor overload protection", RootCauses: []string{"Dirty condenser", "Low refrigerant"}, DiagnosticSteps: []string{"Clean condenser", "Check refrigerant"}, TestPoints: []string{"Discharge pressure: 250-350 PSI"}, ResetProcedure: []string{"Turn off power", "Clean condenser", "Power cycle"}, PartsLikelyNeeded: []string{"Overload protector"}, RelatedCodes: []string{"E6", "E7"}},
		{Code: "E6", Name: "Compressor Failure", Brand: "Fujitsu", Subsystem: "compressor", Severity: "critical", Description: "Compressor not running", RootCauses: []string{"Compressor failed", "Electrical issue"}, DiagnosticSteps: []string{"Test compressor winding", "Check electrical"}, TestPoints: []string{"Compressor U-V: 1-5Ω"}, ResetProcedure: []string{"Call service"}, PartsLikelyNeeded: []string{"Compressor"}, RelatedCodes: []string{"E5", "E7"}},
		{Code: "E7", Name: "Outdoor Fan Motor Error", Brand: "Fujitsu", Subsystem: "outdoor", Severity: "critical", Description: "Outdoor fan motor error", RootCauses: []string{"Motor failed", "Capacitor failed"}, DiagnosticSteps: []string{"Check motor", "Test capacitor"}, TestPoints: []string{"Motor: 10-50Ω"}, ResetProcedure: []string{"Turn off power", "Clean fan", "Turn on"}, PartsLikelyNeeded: []string{"Fan motor", "Capacitor"}, RelatedCodes: []string{"E5", "E6"}},
		{Code: "E8", Name: "Indoor Temperature Sensor Error", Brand: "Fujitsu", Subsystem: "indoor", Severity: "warning", Description: "Indoor room sensor fault", RootCauses: []string{"Sensor failed", "Connector loose"}, DiagnosticSteps: []string{"Test sensor", "Check connector"}, TestPoints: []string{"Sensor: 10kΩ at 25°C"}, ResetProcedure: []string{"Reconnect sensor", "Power cycle"}, PartsLikelyNeeded: []string{"Temperature sensor"}, RelatedCodes: []string{"AL", "E1"}},
	},
	"Elgin": {
		{Code: "E0", Name: "Indoor Fan Motor Error", Brand: "Elgin", Subsystem: "indoor", Severity: "critical", Description: "Indoor fan motor error", RootCauses: []string{"Motor failed", "Capacitor failed"}, DiagnosticSteps: []string{"Check motor", "Test capacitor"}, TestPoints: []string{"Motor: 10-50Ω"}, ResetProcedure: []string{"Turn off power", "Clean fan", "Turn on"}, PartsLikelyNeeded: []string{"Fan motor", "Capacitor"}, RelatedCodes: []string{"E1", "E5"}},
		{Code: "E1", Name: "Communication Error", Brand: "Elgin", Subsystem: "communication", Severity: "critical", Description: "Communication failure", RootCauses: []string{"Wire broken", "Connector loose"}, DiagnosticSteps: []string{"Check wiring", "Verify connectors"}, TestPoints: []string{"Communication: 12V DC"}, ResetProcedure: []string{"Check connections", "Power cycle"}, PartsLikelyNeeded: []string{"Wiring harness"}, RelatedCodes: []string{"E0", "E2"}},
		{Code: "E2", Name: "Outdoor Fan Motor Error", Brand: "Elgin", Subsystem: "outdoor", Severity: "critical", Description: "Outdoor fan motor error", RootCauses: []string{"Motor failed", "Capacitor failed"}, DiagnosticSteps: []string{"Check motor", "Test capacitor"}, TestPoints: []string{"Motor: 10-50Ω"}, ResetProcedure: []string{"Turn off power", "Clean fan", "Turn on"}, PartsLikelyNeeded: []string{"Fan motor", "Capacitor"}, RelatedCodes: []string{"E0", "E5"}},
		{Code: "E5", Name: "Overload Protection", Brand: "Elgin", Subsystem: "compressor", Severity: "critical", Description: "Compressor overload", RootCauses: []string{"Dirty condenser", "Low refrigerant"}, DiagnosticSteps: []string{"Clean condenser", "Check refrigerant"}, TestPoints: []string{"Discharge: 250-350 PSI"}, ResetProcedure: []string{"Turn off power", "Clean condenser", "Power cycle"}, PartsLikelyNeeded: []string{"Overload protector"}, RelatedCodes: []string{"E6", "E2"}},
		{Code: "E6", Name: "Compressor Error", Brand: "Elgin", Subsystem: "compressor", Severity: "critical", Description: "Compressor not running", RootCauses: []string{"Compressor failed", "Contactor failed"}, DiagnosticSteps: []string{"Test compressor winding", "Check contactor"}, TestPoints: []string{"Compressor U-V: 1-5Ω"}, ResetProcedure: []string{"Call service"}, PartsLikelyNeeded: []string{"Compressor", "Contactor"}, RelatedCodes: []string{"E5"}},
	},
	"Carrier": {
		{Code: "E0", Name: "Indoor Fan Motor Error", Brand: "Carrier", Subsystem: "indoor", Severity: "critical", Description: "Indoor fan motor error", RootCauses: []string{"Motor failed", "Capacitor failed", "PCB failed"}, DiagnosticSteps: []string{"Check motor", "Test capacitor", "Check voltage"}, TestPoints: []string{"Motor: 10-50Ω"}, ResetProcedure: []string{"Turn off power", "Clean fan", "Turn on"}, PartsLikelyNeeded: []string{"Fan motor", "Capacitor"}, RelatedCodes: []string{"E1", "E8"}},
		{Code: "E1", Name: "Communication Error", Brand: "Carrier", Subsystem: "communication", Severity: "critical", Description: "Indoor/outdoor communication error", RootCauses: []string{"Wire broken", "Connector loose"}, DiagnosticSteps: []string{"Check wiring", "Check connectors"}, TestPoints: []string{"Communication: 12V DC"}, ResetProcedure: []string{"Check connections", "Power cycle"}, PartsLikelyNeeded: []string{"Wiring harness"}, RelatedCodes: []string{"E0", "E2"}},
		{Code: "E2", Name: "Outdoor Fan Motor Error", Brand: "Carrier", Subsystem: "outdoor", Severity: "critical", Description: "Outdoor fan motor error", RootCauses: []string{"Motor failed", "Capacitor failed"}, DiagnosticSteps: []string{"Check motor", "Test capacitor"}, TestPoints: []string{"Motor: 10-50Ω"}, ResetProcedure: []string{"Turn off power", "Clean fan", "Turn on"}, PartsLikelyNeeded: []string{"Fan motor", "Capacitor"}, RelatedCodes: []string{"E0", "E5"}},
		{Code: "E5", Name: "Overload Protection", Brand: "Carrier", Subsystem: "compressor", Severity: "critical", Description: "Compressor overload protection", RootCauses: []string{"Dirty condenser", "Low refrigerant", "Fan not working"}, DiagnosticSteps: []string{"Clean condenser", "Check refrigerant", "Verify fan"}, TestPoints: []string{"Discharge pressure: 250-350 PSI"}, ResetProcedure: []string{"Turn off power", "Clean condenser", "Power cycle"}, PartsLikelyNeeded: []string{"Overload protector"}, RelatedCodes: []string{"E6", "E8"}},
		{Code: "E6", Name: "Compressor Error", Brand: "Carrier", Subsystem: "compressor", Severity: "critical", Description: "Compressor not running", RootCauses: []string{"Compressor failed", "Contactor failed"}, DiagnosticSteps: []string{"Test compressor winding", "Check contactor"}, TestPoints: []string{"Compressor U-V: 1-5Ω"}, ResetProcedure: []string{"Call service"}, PartsLikelyNeeded: []string{"Compressor", "Contactor"}, RelatedCodes: []string{"E5", "E8"}},
		{Code: "E8", Name: "High Pressure Error", Brand: "Carrier", Subsystem: "outdoor", Severity: "critical", Description: "High pressure protection", RootCauses: []string{"Dirty condenser", "Fan not working", "Blocked airflow"}, DiagnosticSteps: []string{"Clean condenser", "Verify fan", "Check HP switch"}, TestPoints: []string{"HP switch: open when triggered"}, ResetProcedure: []string{"Turn off power", "Clean condenser", "Wait 5 min", "Turn on"}, PartsLikelyNeeded: []string{"HP switch", "Fan motor"}, RelatedCodes: []string{"E5", "E6"}},
	},
	"Hisense": {
		{Code: "E0", Name: "Indoor Fan Motor Error", Brand: "Hisense", Subsystem: "indoor", Severity: "critical", Description: "Indoor fan motor error", RootCauses: []string{"Motor failed", "Capacitor failed"}, DiagnosticSteps: []string{"Check motor", "Test capacitor"}, TestPoints: []string{"Motor: 10-50Ω"}, ResetProcedure: []string{"Turn off power", "Clean fan", "Turn on"}, PartsLikelyNeeded: []string{"Fan motor", "Capacitor"}, RelatedCodes: []string{"E1", "E4"}},
		{Code: "E1", Name: "Communication Error", Brand: "Hisense", Subsystem: "communication", Severity: "critical", Description: "Communication failure", RootCauses: []string{"Wire broken", "Connector loose"}, DiagnosticSteps: []string{"Check wiring", "Verify connectors"}, TestPoints: []string{"Communication: 12V DC"}, ResetProcedure: []string{"Check connections", "Power cycle"}, PartsLikelyNeeded: []string{"Wiring harness"}, RelatedCodes: []string{"E0", "E2"}},
		{Code: "E2", Name: "Outdoor Fan Motor Error", Brand: "Hisense", Subsystem: "outdoor", Severity: "critical", Description: "Outdoor fan motor error", RootCauses: []string{"Motor failed", "Capacitor failed"}, DiagnosticSteps: []string{"Check motor", "Test capacitor"}, TestPoints: []string{"Motor: 10-50Ω"}, ResetProcedure: []string{"Turn off power", "Clean fan", "Turn on"}, PartsLikelyNeeded: []string{"Fan motor", "Capacitor"}, RelatedCodes: []string{"E0", "E4"}},
		{Code: "E4", Name: "Temperature Sensor Error", Brand: "Hisense", Subsystem: "indoor", Severity: "warning", Description: "Temperature sensor fault", RootCauses: []string{"Sensor failed", "Connector loose"}, DiagnosticSteps: []string{"Test sensor", "Check connector"}, TestPoints: []string{"Sensor: 10kΩ at 25°C"}, ResetProcedure: []string{"Reconnect sensor", "Power cycle"}, PartsLikelyNeeded: []string{"Temperature sensor"}, RelatedCodes: []string{"E0", "E2"}},
		{Code: "F1", Name: "High Pressure Protection", Brand: "Hisense", Subsystem: "outdoor", Severity: "critical", Description: "High pressure switch activated", RootCauses: []string{"Dirty condenser", "Fan not working"}, DiagnosticSteps: []string{"Clean condenser", "Verify fan", "Check HP switch"}, TestPoints: []string{"HP switch: open when triggered"}, ResetProcedure: []string{"Turn off power", "Clean condenser", "Wait 5 min", "Turn on"}, PartsLikelyNeeded: []string{"HP switch", "Fan motor"}, RelatedCodes: []string{"E2", "E4"}},
	},
}

// AllErrorCodes returns all error codes flattened
func AllErrorCodes() []ErrorCode {
	var all []ErrorCode
	for _, codes := range BrandErrorCodes {
		all = append(all, codes...)
	}
	return all
}

// GetErrorCodeByBrand returns error codes for a specific brand
func GetErrorCodeByBrand(brand string) []ErrorCode {
	brandLower := strings.ToLower(brand)
	var result []ErrorCode
	for b, codes := range BrandErrorCodes {
		if strings.ToLower(b) == brandLower || strings.Contains(strings.ToLower(b), brandLower) {
			result = append(result, codes...)
		}
	}
	return result
}

// GetErrorCode returns a specific error code by brand and code
func GetErrorCode(brand, code string) *ErrorCode {
	brandLower := strings.ToLower(brand)
	codeUpper := strings.ToUpper(code)
	for b, codes := range BrandErrorCodes {
		if strings.ToLower(b) == brandLower || strings.Contains(strings.ToLower(b), brandLower) {
			for _, ec := range codes {
				if strings.ToUpper(ec.Code) == codeUpper {
					return &ec
				}
			}
		}
	}
	return nil
}

// SearchErrorCodes searches error codes by keyword in name, description, or root cause
func SearchErrorCodes(keyword string) []ErrorCode {
	keywordLower := strings.ToLower(keyword)
	var result []ErrorCode
	for _, codes := range BrandErrorCodes {
		for _, ec := range codes {
			if strings.Contains(strings.ToLower(ec.Name), keywordLower) ||
				strings.Contains(strings.ToLower(ec.Description), keywordLower) ||
				strings.Contains(strings.ToLower(ec.Code), keywordLower) {
				result = append(result, ec)
			}
		}
	}
	return result
}
