#!/usr/bin/env bash
# =============================================================================
# env-vault-sync.sh — SRE-Pro Environment Vault Sync
# =============================================================================
# Canonical .env → .env.example with ${VAR} placeholders
# ZFS snapshot before sync (tank vault)
# LLM-friendly: agents read .env.example and code with process.env.VAR
#
# Usage:
#   bash scripts/env-vault-sync.sh              # sync monorepo
#   bash scripts/env-vault-sync.sh --dry-run    # preview changes
#   bash scripts/env-vault-sync.sh --no-snapshot # skip ZFS snapshot
#
# Auto-trigger: add to .git/hooks/post-commit or pre-push
# =============================================================================

set -euo pipefail

MONOREPO="${MONOREPO:-/srv/monorepo}"
ENV_FILE="$MONOREPO/.env"
ENV_EXAMPLE="$MONOREPO/.env.example"
ZFS_DATASET="${ZFS_DATASET:-tank/monorepo}"
DRY_RUN=false
SKIP_SNAPSHOT=false

GREEN='\033[0;32m'; CYAN='\033[0;36m'; YELLOW='\033[1;33m'; NC='\033[0m'
log()  { echo -e "${GREEN}[env-vault]${NC} $(date +%H:%M:%S) $*"; }
info() { echo -e "${CYAN}           ${NC} $*"; }
warn() { echo -e "${YELLOW}           ${NC} $*"; }

for arg in "$@"; do
    case "$arg" in
        --dry-run) DRY_RUN=true ;;
        --no-snapshot) SKIP_SNAPSHOT=true ;;
    esac
done

# ─── ZFS Snapshot (vault backup) ────────────────────────────────────────────
snapshot_env() {
    if $SKIP_SNAPSHOT; then
        log "Snapshot SKIPPED (--no-snapshot)"
        return 0
    fi

    # Only proceed if ZFS is available
    if ! command -v zfs &>/dev/null; then
        warn "ZFS not available — skipping snapshot"
        return 0
    fi

    if ! zfs list "$ZFS_DATASET" &>/dev/null; then
        warn "ZFS dataset $ZFS_DATASET not found — skipping snapshot"
        return 0
    fi

    local snap_name="${ZFS_DATASET}@env-vault-$(date +%Y%m%d-%H%M%S)"
    if sudo zfs snapshot "$snap_name" 2>/dev/null; then
        log "ZFS snapshot: $snap_name"
    else
        warn "ZFS snapshot failed — continuing without snapshot"
    fi
}

# ─── Secret Detection ───────────────────────────────────────────────────────
# Returns 0 if the variable should be redacted (secret)
is_secret() {
    local name="$1"
    local value="$2"

    # Rule 1: Name contains secret keywords
    case "$name" in
        *KEY|*_KEY|*_API_KEY|*_SECRET|*_TOKEN|*_PASSWORD|*_AUTH*|*_CREDS*|*_PRIVATE*|*_BOT_TOKEN*|*_MASTER_KEY*|*_FACADE_KEY*|*_LICENSE*)
            return 0 ;;
    esac

    # Rule 2: Value looks like a crypto key (base64, hex, JWT)
    # Long string with mix of upper/lower/digits/special
    local len=${#value}
    if [[ $len -ge 30 ]]; then
        # JWT pattern: eyJ...
        if [[ "$value" =~ ^eyJ[a-zA-Z0-9_-]+\.[a-zA-Z0-9_-]+\.[a-zA-Z0-9_-]+$ ]]; then
            return 0
        fi
        # sk- prefix (API keys)
        if [[ "$value" =~ ^sk-[a-zA-Z0-9_-]{20,} ]]; then
            return 0
        fi
        # Contains special chars typical of secrets
        if [[ "$value" =~ [\-\+_/=]{4,} ]] && [[ ! "$value" =~ ^https?:// ]]; then
            return 0
        fi
    fi

    # Not a secret
    return 1
}

# ─── Sync .env → .env.example ──────────────────────────────────────────────
sync_env() {
    if [[ ! -f "$ENV_FILE" ]]; then
        echo "ERROR: $ENV_FILE not found" >&2
        exit 1
    fi

    local secret_count=0
    local public_count=0
    local total_count=0

    local output
    output=$(mktemp)

    {
        cat <<'HEADER'
# =============================================================================
# .env.example — AUTO-GENERATED by scripts/env-vault-sync.sh
# =============================================================================
# DO NOT EDIT manually. Edit /srv/monorepo/.env and run:
#   bash scripts/env-vault-sync.sh
#
# Anti-Hardcode Pattern for LLM agents:
#   Secrets use ${VAR_NAME} placeholders.
#   To read in code: process.env.VAR_NAME
#   Example: const key = process.env.MINIMAX_API_KEY; // ✅
#            const key = "sk-cp-...";                // ❌ HARDCODED
#
# ZFS Vault: tank/monorepo@env-vault-*
# Canonical: /srv/monorepo/.env (gitignored, chmod 600)
# =============================================================================

HEADER

        local current_section=""
        while IFS= read -r line || [[ -n "$line" ]]; do
            # Preserve comments and empty lines
            if [[ -z "$line" ]]; then
                echo ""
                continue
            fi
            if [[ "$line" =~ ^[[:space:]]*# ]]; then
                echo "$line"
                continue
            fi

            # Parse VAR=value
            if [[ "$line" =~ ^([A-Za-z_][A-Za-z0-9_]*)=(.*) ]]; then
                local var_name="${BASH_REMATCH[1]}"
                local var_value="${BASH_REMATCH[2]}"
                total_count=$((total_count + 1))

                # Skip empty values
                if [[ -z "$var_value" ]]; then
                    echo "${var_name}="
                    continue
                fi

                # Is this a secret?
                if is_secret "$var_name" "$var_value"; then
                    echo "${var_name}=\${${var_name}}"
                    secret_count=$((secret_count + 1))
                else
                    echo "${var_name}=${var_value}"
                    public_count=$((public_count + 1))
                fi
            else
                echo "$line"
            fi
        done < "$ENV_FILE"

        cat <<'FOOTER'

# =============================================================================
# Generated: SYNC_TIMESTAMP
# Secrets redacted: SECRET_COUNT | Public values kept: PUBLIC_COUNT | Total: TOTAL_COUNT
# Next sync: run 'bash scripts/env-vault-sync.sh' after editing .env
# =============================================================================
FOOTER
    } > "$output"

    # Replace placeholders
    sed -i "s/SYNC_TIMESTAMP/$(date -u +%Y-%m-%dT%H:%M:%SZ)/" "$output"
    sed -i "s/SECRET_COUNT/$secret_count/" "$output"
    sed -i "s/PUBLIC_COUNT/$public_count/" "$output"
    sed -i "s/TOTAL_COUNT/$total_count/" "$output"

    log "Scan: $total_count vars → $secret_count secrets redacted, $public_count public kept"

    if $DRY_RUN; then
        log "DRY RUN — preview:"
        diff --color=auto "$ENV_EXAMPLE" "$output" 2>/dev/null || true
        rm -f "$output"
        return 0
    fi

    # Check if changed
    if [[ -f "$ENV_EXAMPLE" ]] && diff -q "$ENV_EXAMPLE" "$output" &>/dev/null; then
        info "No changes detected — .env.example is up to date"
        rm -f "$output"
        return 0
    fi

    # Write and secure
    cp "$output" "$ENV_EXAMPLE"
    rm -f "$output"
    chmod 644 "$ENV_EXAMPLE"

    log "Written: $ENV_EXAMPLE ($(wc -l < "$ENV_EXAMPLE") lines)"
}

# ─── Sync to Workspace Apps ────────────────────────────────────────────────
sync_to_apps() {
    local apps=("api" "web" "orchestrator")
    local synced=0

    for app in "${apps[@]}"; do
        local app_dir="$MONOREPO/apps/$app"
        local app_env="$app_dir/.env"

        if [[ -d "$app_dir" ]]; then
            # Create symlink or copy .env reference
            if [[ -L "$app_env" ]]; then
                info "apps/$app/.env → symlink OK"
            elif [[ -f "$app_env" ]]; then
                warn "apps/$app/.env is a real file (not symlink) — manual check needed"
            else
                ln -sf "$ENV_FILE" "$app_env" 2>/dev/null && {
                    info "apps/$app/.env → linked to canonical .env"
                    synced=$((synced + 1))
                }
            fi
        fi
    done

    [[ $synced -gt 0 ]] && log "Linked $synced app(s) to canonical .env"
}

# ─── Main ──────────────────────────────────────────────────────────────────
main() {
    if [[ ! -f "$ENV_FILE" ]]; then
        echo "FATAL: Canonical .env not found at $ENV_FILE" >&2
        exit 1
    fi

    log "Starting env vault sync"
    snapshot_env
    sync_env
    sync_to_apps
    log "Done"
}

main
