#!/usr/bin/env bash
# env-sync.sh — Sync .env.example from .env (canonical source)
#
# Usage:
#   bash scripts/env-sync.sh                  # sync monorepo .env.example
#   bash scripts/env-sync.sh /path/to/.env    # sync specific .env
#
# What it does:
#   - Reads the .env file (real values, gitignored)
#   - Replaces SECRET values with ${VAR_NAME} placeholders
#   - Keeps non-secret values (ports, URLs, feature flags) as-is
#   - Writes to .env.example (tracked in git)
#
# Pattern rules:
#   Secrets → ${VAR_NAME} (any VAR that looks like a key/token/password/secret)
#   Non-secrets → actual value (ports, URLs to localhost, numbers, flags)
#
# To run automatically on .env change: add to git post-commit hook or call manually
set -euo pipefail

SOURCE_ENV="${1:-/srv/monorepo/.env}"
TARGET_ENVEXAMPLE="${SOURCE_ENV%.env}.env.example"

if [[ ! -f "$SOURCE_ENV" ]]; then
    echo "ERROR: $SOURCE_ENV not found"
    exit 1
fi

echo "[env-sync] Syncing $SOURCE_ENV → $TARGET_ENVEXAMPLE"

# Detect secret variables (heuristic: names containing KEY, TOKEN, SECRET, PASSWORD, API_KEY, etc.)
is_secret_var() {
    local var_name="$1"
    case "$var_name" in
        *KEY*|*TOKEN*|*SECRET*|*PASSWORD*|*BOT_TOKEN*|*AUTH*|*CREDS*|*PRIVATE*)
            return 0
            ;;
        *)
            return 1
            ;;
    esac
}

# Read .env and generate .env.example
{
    echo "# =========================================="
    echo "# Env Template — AUTO-GENERATED by scripts/env-sync.sh"
    echo "# DO NOT EDIT MANUALLY — edit .env and run: bash scripts/env-sync.sh"
    echo "# Source: $SOURCE_ENV"
    echo "# =========================================="
    echo ""

    while IFS= read -r line || [[ -n "$line" ]]; do
        # Skip empty lines and comments
        if [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]]; then
            echo "$line"
            continue
        fi

        # Parse VAR=value
        if [[ "$line" =~ ^([A-Za-z_][A-Za-z0-9_]*)=(.*) ]]; then
            var_name="${BASH_REMATCH[1]}"
            var_value="${BASH_REMATCH[2]}"

            # Remove existing ${VAR} placeholders from value (cleanup)
            var_value="${var_value//\$\{$var_name\}/}"

            if is_secret_var "$var_name"; then
                echo "${var_name}=\${${var_name}}"
            else
                echo "${var_name}=${var_value}"
            fi
        else
            echo "$line"
        fi
    done < <(grep -v '^#' "$SOURCE_ENV" | grep '=')
} > "$TARGET_ENVEXAMPLE"

chmod 644 "$TARGET_ENVEXAMPLE"
echo "[env-sync] Done — $(wc -l < "$TARGET_ENVEXAMPLE") lines written to $TARGET_ENVEXAMPLE"
