#!/bin/bash
# SPEC-AUTOMATOR — Main Orchestrator
# Zero-touch: SPEC → Loop → Commit → PR → Sync → /clear → New Branch

set -e

IDEA="$1"
TIMESTAMP=$(date +%s)
RANDOM_HEX=$(openssl rand -hex 3)
BRANCH_NAME="feat/${TIMESTAMP}-${RANDOM_HEX}"
LOG_FILE="/tmp/spec-automator-${TIMESTAMP}.log"

log() { echo "[$(date '+%H:%M:%S')] $1" | tee -a "$LOG_FILE"; }

if [ -z "$IDEA" ]; then
    echo "Usage: spec-automator.sh '<idea>'"
    echo "Example: spec-automator.sh 'sistema de notificações push'"
    exit 1
fi

log "🚀 SPEC-AUTOMATOR started"
log "Idea: $IDEA"
log "Branch will be: $BRANCH_NAME"

# Start context monitor in background
log "Starting context monitor..."
bash /srv/monorepo/scripts/context-monitor.sh &
CONTEXT_PID=$!
log "Context monitor PID: $CONTEXT_PID"

# Create SPEC from idea
log "Creating SPEC..."
SPEC_FILE="/srv/monorepo/docs/SPECS/SPEC-$(date +%Y%m%d%H%M%S)-auto.md"

cat > "$SPEC_FILE" << EOF
# SPEC-AUTO-$(date +%Y%m%d%H%M%S) — $IDEA

**Date:** $(date +%Y-%m-%d)
**Status:** IN_PROGRESS
**Type:** Auto-generated by SPEC-AUTOMATOR

---

## Objective

$IDEA

---

## Implementation

This SPEC will be executed by Claude Code CLI AI which will:
1. Read this SPEC
2. Choose appropriate loop (/computer-loop or /cursor-loop)
3. Execute all tasks
4. On success: commit → PR → sync → /clear → new branch

---

## Acceptance Criteria

- [ ] AI chose appropriate loop complexity
- [ ] All tasks completed successfully
- [ ] Commit + PR created
- [ ] AI-CONTEXT synced
- [ ] Terminal /clear executed
- [ ] New random branch created

EOF

log "SPEC created: $SPEC_FILE"

# Trigger AI execution
# The AI (Claude Code CLI) will read the SPEC and decide what to do
# This script just sets up the environment

log "📋 SPEC ready. AI will now read and execute."
log "Waiting for AI to complete loop execution..."

# Wait for context monitor to signal completion or failure
# The AI handles the loop execution itself

# When AI completes, completion-handler.sh will be called
log "AI execution complete. Running completion handler..."

# Cleanup context monitor
kill $CONTEXT_PID 2>/dev/null || true

log "✅ SPEC-AUTOMATOR execution phase complete"
log "Next: manual trigger of completion-handler.sh if needed"