runner:
  capacity: 2
  timeout: 3h
  ephemeral: true
  labels:
    - "ubuntu-latest:docker://docker.gitea.com/runner-images:ubuntu-latest"
    - "ubuntu-22.04:docker://docker.gitea.com/runner-images:ubuntu-22.04"

cache:
  enabled: true
  dir: /data/actcache

container:
  network: "gitea"
  privileged: true
  force_pull: true